export const ORANGE         = '#FF8F00'
export const GREEN          = '#4CAF50'
export const RED            = '#E53935'
export const BG             = '#111111'
export const CARD           = '#1C1C1E'
export const BORDER         = '#2C2C2E'
export const TEXT_PRIMARY   = '#FFFFFF'
export const TEXT_SECONDARY = '#888888'
