// Genererad från GIF-mappningen mot ExerciseDB-paketet. Används där bara
// övningsNAMNET finns (flödeskort, passdetaljer), övriga vyer läser
// image_path från databasen. Egna övningar saknas medvetet.

export const EXERCISE_IMAGES: Record<string, string> = {
  'Ab wheel': 'ab-wheel.gif',
  'Arnold press': 'arnold-press.gif',
  'Axellyft med kabel': 'axellyft-med-kabel.gif',
  'Bakre deltalyft': 'bakre-deltalyft.gif',
  'Bakre deltalyft i kabel': 'bakre-deltalyft-i-kabel.gif',
  'Bencurl liggande': 'bencurl-liggande.gif',
  'Benextension': 'benextension.gif',
  'Benlyft liggande': 'benlyft-liggande.gif',
  'Benpress': 'benpress.gif',
  'Bicepscurl': 'bicepscurl.gif',
  'Box squat': 'box-squat.gif',
  'Bulgariska utfall': 'bulgariska-utfall.gif',
  'Bänkpress': 'bankpress.gif',
  'Chin-ups': 'chin-ups.gif',
  'Crunches': 'crunches.gif',
  'Decline bänkpress': 'decline-bankpress.gif',
  'Dips': 'dips.gif',
  'Dragon flag': 'dragon-flag.gif',
  'Enarms hantelrodd': 'enarms-hantelrodd.gif',
  'Enarms kabelcurl': 'enarms-kabelcurl.gif',
  'Enarms kabelrodd': 'enarms-kabelrodd.gif',
  'Face pulls': 'face-pulls.gif',
  'Farmers walk': 'farmers-walk.gif',
  'Flyes med hantlar': 'flyes-med-hantlar.gif',
  'Frivändning': 'frivandning.gif',
  'Front squat': 'front-squat.gif',
  'Frontlyft': 'frontlyft.gif',
  'Frontlyft i kabel': 'frontlyft-i-kabel.gif',
  'Genomdrag med kabel': 'genomdrag-med-kabel.gif',
  'Glute kickback i kabel': 'glute-kickback-i-kabel.gif',
  'Goblet squat': 'goblet-squat.gif',
  'Good mornings': 'good-mornings.gif',
  'Hack squat': 'hack-squat.gif',
  'Hammercurl': 'hammercurl.gif',
  'Handledscurl': 'handledscurl.gif',
  'Hantelpress axlar': 'hantelpress-axlar.gif',
  'Hantelpress liggande': 'hantelpress-liggande.gif',
  'Hip thrust': 'hip-thrust.gif',
  'Hyperextensions': 'hyperextensions.gif',
  'Hängande benlyft': 'hangande-benlyft.gif',
  'Höftabduktion i kabel': 'hoftabduktion-i-kabel.gif',
  'Kabelbiceps': 'kabelbiceps.gif',
  'Kabelcrunch': 'kabelcrunch.gif',
  'Kabelcurl med rep': 'kabelcurl-med-rep.gif',
  'Kabelflyes': 'kabelflyes.gif',
  'Kabelkorsning': 'kabelkorsning.gif',
  'Kabelpress': 'kabelpress.gif',
  'Kabelpullover': 'kabelpullover.gif',
  'Kabelrodd sittande': 'kabelrodd-sittande.gif',
  'Kabeltriceps över huvud': 'kabeltriceps-over-huvud.gif',
  'Kabelvridning': 'kabelvridning.gif',
  'Kettlebell swing': 'kettlebell-swing.gif',
  'Knäböj': 'knaboj.gif',
  'Koncentrationscurl': 'koncentrationscurl.gif',
  'Latsdrag bakåt': 'latsdrag-bakat.gif',
  'Latsdrag framifrån': 'latsdrag-framifran.gif',
  'Latsdrag med raka armar': 'latsdrag-med-raka-armar.gif',
  'Latsdrag smalt grepp': 'latsdrag-smalt-grepp.gif',
  'Lutande bänkpress': 'lutande-bankpress.gif',
  'Lutande hantelpress': 'lutande-hantelpress.gif',
  'Lutande kabelflyes': 'lutande-kabelflyes.gif',
  'Marklyft': 'marklyft.gif',
  'Militärpress': 'militarpress.gif',
  'Mountain climbers': 'mountain-climbers.gif',
  'Nordic curl': 'nordic-curl.gif',
  'Omvänd flyes': 'omvand-flyes.gif',
  'Pallof press': 'pallof-press.gif',
  'Pec deck': 'pec-deck.gif',
  'Pistol squat': 'pistol-squat.gif',
  'Plankan': 'plankan.gif',
  'Preacher curl': 'preacher-curl.gif',
  'Pull-ups': 'pull-ups.gif',
  'Push press': 'push-press.gif',
  'Push-ups': 'push-ups.gif',
  'Rack pull': 'rack-pull.gif',
  'Rodd med skivstång': 'rodd-med-skivstang.gif',
  'Rumänsk marklyft': 'rumansk-marklyft.gif',
  'Russian twist': 'russian-twist.gif',
  'Shrugs med hantlar': 'shrugs-med-hantlar.gif',
  'Shrugs med skivstång': 'shrugs-med-skivstang.gif',
  'Sidolyft': 'sidolyft.gif',
  'Sidoplanka': 'sidoplanka.gif',
  'Sittande bencurl': 'sittande-bencurl.gif',
  'Sittande vadpress': 'sittande-vadpress.gif',
  'Situps': 'situps.gif',
  'Skull crushers': 'skull-crushers.gif',
  'Smalbänkpress': 'smalbankpress.gif',
  'Steg-ups': 'steg-ups.gif',
  'Stående kabelrodd': 'staende-kabelrodd.gif',
  'Sumo marklyft': 'sumo-marklyft.gif',
  'T-bar rodd': 't-bar-rodd.gif',
  'Thrusters': 'thrusters.gif',
  'Triceps kickback': 'triceps-kickback.gif',
  'Tricepspress smal': 'tricepspress-smal.gif',
  'Tricepsstötning kabel': 'tricepsstotning-kabel.gif',
  'Tricepsstötning med rep': 'tricepsstotning-med-rep.gif',
  'Upright row': 'upright-row.gif',
  'Utfall': 'utfall.gif',
  'Vadpress stående': 'vadpress-staende.gif',
}

export function exerciseImageFor(name: string): string | null {
  return EXERCISE_IMAGES[name] ?? null
}

/** Publik URL utan supabase-klienten: flödeskorten renderas även i miljöer
    (tester) där klienten inte finns, och bucketen är publik ändå. */
export function exerciseImageUrlFor(name: string): string | null {
  const file = EXERCISE_IMAGES[name]
  const base = process.env.EXPO_PUBLIC_SUPABASE_URL
  if (!file || !base) return null
  return `${base}/storage/v1/object/public/exercise-images/${file}`
}
