// Genererad från GIF-mappningen mot ExerciseDB-paketet. Används där bara
// övningsNAMNET finns (flödeskort, passdetaljer), övriga vyer läser
// image_path från databasen. Egna övningar saknas medvetet.

export const EXERCISE_IMAGES: Record<string, string> = {
  'Ab wheel': 'ab-wheel.gif',
  'Arnold press': 'arnold-press.gif',
  'Axellyft med kabel': 'axellyft-med-kabel.gif',
  'Bakre deltalyft': 'bakre-deltalyft.gif',
  'Bakre deltalyft i kabel': 'bakre-deltalyft-i-kabel.gif',
  'Bencurl liggande': 'bencurl-liggande.gif',
  'Benextension': 'benextension.gif',
  'Benlyft liggande': 'benlyft-liggande.gif',
  'Benpress': 'benpress.gif',
  'Bicepscurl': 'bicepscurl.gif',
  'Box squat': 'box-squat.gif',
  'Bulgariska utfall': 'bulgariska-utfall.gif',
  'Bänkpress': 'bankpress.gif',
  'Chin-ups': 'chin-ups.gif',
  'Crunches': 'crunches.gif',
  'Decline bänkpress': 'decline-bankpress.gif',
  'Dips': 'dips.gif',
  'Dragon flag': 'dragon-flag.gif',
  'Enarms hantelrodd': 'enarms-hantelrodd.gif',
  'Enarms kabelcurl': 'enarms-kabelcurl.gif',
  'Enarms kabelrodd': 'enarms-kabelrodd.gif',
  'Face pulls': 'face-pulls.gif',
  'Farmers walk': 'farmers-walk.gif',
  'Flyes med hantlar': 'flyes-med-hantlar.gif',
  'Frivändning': 'frivandning.gif',
  'Front squat': 'front-squat.gif',
  'Frontlyft': 'frontlyft.gif',
  'Frontlyft i kabel': 'frontlyft-i-kabel.gif',
  'Genomdrag med kabel': 'genomdrag-med-kabel.gif',
  'Glute kickback i kabel': 'glute-kickback-i-kabel.gif',
  'Goblet squat': 'goblet-squat.gif',
  'Good mornings': 'good-mornings.gif',
  'Hack squat': 'hack-squat.gif',
  'Hammercurl': 'hammercurl.gif',
  'Handledscurl': 'handledscurl.gif',
  'Hantelpress axlar': 'hantelpress-axlar.gif',
  'Hantelpress liggande': 'hantelpress-liggande.gif',
  'Hip thrust': 'hip-thrust.gif',
  'Hyperextensions': 'hyperextensions.gif',
  'Hängande benlyft': 'hangande-benlyft.gif',
  'Höftabduktion i kabel': 'hoftabduktion-i-kabel.gif',
  'Kabelbiceps': 'kabelbiceps.gif',
  'Kabelcrunch': 'kabelcrunch.gif',
  'Kabelcurl med rep': 'kabelcurl-med-rep.gif',
  'Kabelflyes': 'kabelflyes.gif',
  'Kabelkorsning': 'kabelkorsning.gif',
  'Kabelpress': 'kabelpress.gif',
  'Kabelpullover': 'kabelpullover.gif',
  'Kabelrodd sittande': 'kabelrodd-sittande.gif',
  'Kabeltriceps över huvud': 'kabeltriceps-over-huvud.gif',
  'Kabelvridning': 'kabelvridning.gif',
  'Kettlebell swing': 'kettlebell-swing.gif',
  'Knäböj': 'knaboj.gif',
  'Koncentrationscurl': 'koncentrationscurl.gif',
  'Latsdrag bakåt': 'latsdrag-bakat.gif',
  'Latsdrag framifrån': 'latsdrag-framifran.gif',
  'Latsdrag med raka armar': 'latsdrag-med-raka-armar.gif',
  'Latsdrag smalt grepp': 'latsdrag-smalt-grepp.gif',
  'Lutande bänkpress': 'lutande-bankpress.gif',
  'Lutande hantelpress': 'lutande-hantelpress.gif',
  'Lutande kabelflyes': 'lutande-kabelflyes.gif',
  'Marklyft': 'marklyft.gif',
  'Militärpress': 'militarpress.gif',
  'Mountain climbers': 'mountain-climbers.gif',
  'Nordic curl': 'nordic-curl.gif',
  'Omvänd flyes': 'omvand-flyes.gif',
  'Pallof press': 'pallof-press.gif',
  'Pec deck': 'pec-deck.gif',
  'Pistol squat': 'pistol-squat.gif',
  'Plankan': 'plankan.gif',
  'Preacher curl': 'preacher-curl.gif',
  'Pull-ups': 'pull-ups.gif',
  'Push press': 'push-press.gif',
  'Push-ups': 'push-ups.gif',
  'Rack pull': 'rack-pull.gif',
  'Rodd med skivstång': 'rodd-med-skivstang.gif',
  'Rumänsk marklyft': 'rumansk-marklyft.gif',
  'Russian twist': 'russian-twist.gif',
  'Shrugs med hantlar': 'shrugs-med-hantlar.gif',
  'Shrugs med skivstång': 'shrugs-med-skivstang.gif',
  'Sidolyft': 'sidolyft.gif',
  'Sidoplanka': 'sidoplanka.gif',
  'Sittande bencurl': 'sittande-bencurl.gif',
  'Sittande vadpress': 'sittande-vadpress.gif',
  'Situps': 'situps.gif',
  'Skull crushers': 'skull-crushers.gif',
  'Smalbänkpress': 'smalbankpress.gif',
  'Steg-ups': 'steg-ups.gif',
  'Stående kabelrodd': 'staende-kabelrodd.gif',
  'Sumo marklyft': 'sumo-marklyft.gif',
  'T-bar rodd': 't-bar-rodd.gif',
  'Thrusters': 'thrusters.gif',
  'Triceps kickback': 'triceps-kickback.gif',
  'Tricepspress smal': 'tricepspress-smal.gif',
  'Tricepsstötning kabel': 'tricepsstotning-kabel.gif',
  'Tricepsstötning med rep': 'tricepsstotning-med-rep.gif',
  'Upright row': 'upright-row.gif',
  'Utfall': 'utfall.gif',
  'Vadpress stående': 'vadpress-staende.gif',
  '3/4 sit-up': 'lib/edb-0001.gif',
  '45° side bend': 'lib/edb-0002.gif',
  'Air bike': 'lib/edb-0003.gif',
  'All fours squad stretch': 'lib/edb-1512.gif',
  'Alternate heel touchers': 'lib/edb-0006.gif',
  'Alternate lateral pulldown': 'lib/edb-0007.gif',
  'Ankle circles': 'lib/edb-1368.gif',
  'Ankle dorsal flexion': 'lib/edb-2761.gif',
  'Archer pull up': 'lib/edb-3293.gif',
  'Archer push up': 'lib/edb-3294.gif',
  'Arm slingers hanging bent knee legs': 'lib/edb-2355.gif',
  'Arm slingers hanging straight legs': 'lib/edb-2333.gif',
  'Back lever': 'lib/edb-3297.gif',
  'Back pec stretch': 'lib/edb-1405.gif',
  'Backward jump': 'lib/edb-1473.gif',
  'Balance board': 'lib/edb-0020.gif',
  'Barbell alternate biceps curl': 'lib/edb-0023.gif',
  'Barbell bench front squat': 'lib/edb-0024.gif',
  'Barbell bent arm pullover': 'lib/edb-1316.gif',
  'Barbell biceps curl (with arm blaster)': 'lib/edb-2407.gif',
  'Barbell clean and press': 'lib/edb-0028.gif',
  'Barbell clean-grip front squat': 'lib/edb-0029.gif',
  'Barbell curl': 'lib/edb-0031.gif',
  'Barbell decline bent arm pullover': 'lib/edb-0034.gif',
  'Barbell decline close grip to skull press': 'lib/edb-0035.gif',
  'Barbell decline pullover': 'lib/edb-1255.gif',
  'Barbell decline wide-grip press': 'lib/edb-0036.gif',
  'Barbell decline wide-grip pullover': 'lib/edb-0037.gif',
  'Barbell drag curl': 'lib/edb-0038.gif',
  'Barbell floor calf raise': 'lib/edb-1370.gif',
  'Barbell front chest squat': 'lib/edb-0039.gif',
  'Barbell front raise': 'lib/edb-0041.gif',
  'Barbell front raise and pullover': 'lib/edb-0040.gif',
  'Barbell full zercher squat': 'lib/edb-1545.gif',
  'Barbell glute bridge': 'lib/edb-1409.gif',
  'Barbell guillotine bench press': 'lib/edb-0045.gif',
  'Barbell high bar squat': 'lib/edb-1436.gif',
  'Barbell incline close grip bench press': 'lib/edb-1719.gif',
  'Barbell incline reverse-grip press': 'lib/edb-0048.gif',
  'Barbell incline row': 'lib/edb-0049.gif',
  'Barbell incline shoulder raise': 'lib/edb-0050.gif',
  'Barbell jefferson squat': 'lib/edb-0051.gif',
  'Barbell jm bench press': 'lib/edb-0052.gif',
  'Barbell jump squat': 'lib/edb-0053.gif',
  'Barbell landmine squat': 'lib/edb-0603.gif',
  'Barbell lateral lunge': 'lib/edb-1410.gif',
  'Barbell leg twist press': 'lib/edb-2811.gif',
  'Barbell low bar squat': 'lib/edb-1435.gif',
  'Barbell lunge': 'lib/edb-0054.gif',
  'Barbell lying back of the head tricep extension': 'lib/edb-1720.gif',
  'Barbell lying close-grip press': 'lib/edb-0055.gif',
  'Barbell lying extension': 'lib/edb-0057.gif',
  'Barbell lying lifting (on hip)': 'lib/edb-0058.gif',
  'Barbell lying preacher curl': 'lib/edb-0059.gif',
  'Barbell lying triceps extension': 'lib/edb-0061.gif',
  'Barbell narrow stance squat': 'lib/edb-0063.gif',
  'Barbell one arm bent over row': 'lib/edb-0064.gif',
  'Barbell one arm floor press': 'lib/edb-0065.gif',
  'Barbell one arm side deadlift': 'lib/edb-0066.gif',
  'Barbell one arm snatch': 'lib/edb-0067.gif',
  'Barbell one leg squat': 'lib/edb-0068.gif',
  'Barbell overhead squat': 'lib/edb-0069.gif',
  'Barbell palms down wrist curl over a bench': 'lib/edb-1411.gif',
  'Barbell palms up wrist curl over a bench': 'lib/edb-1412.gif',
  'Barbell pendlay row': 'lib/edb-3017.gif',
  'Barbell pin presses': 'lib/edb-1751.gif',
  'Barbell press sit-up': 'lib/edb-0071.gif',
  'Barbell prone incline curl': 'lib/edb-0072.gif',
  'Barbell pullover': 'lib/edb-0073.gif',
  'Barbell pullover to press': 'lib/edb-0022.gif',
  'Barbell rear delt raise': 'lib/edb-0075.gif',
  'Barbell rear delt row': 'lib/edb-0076.gif',
  'Barbell rear lunge': 'lib/edb-0078.gif',
  'Barbell reverse close-grip bench press': 'lib/edb-2187.gif',
  'Barbell reverse curl': 'lib/edb-0080.gif',
  'Barbell reverse grip bent over row': 'lib/edb-0118.gif',
  'Barbell reverse grip decline bench press': 'lib/edb-1256.gif',
  'Barbell reverse grip incline bench press': 'lib/edb-1257.gif',
  'Barbell reverse grip incline bench row': 'lib/edb-1317.gif',
  'Barbell reverse grip skullcrusher': 'lib/edb-1721.gif',
  'Barbell reverse preacher curl': 'lib/edb-0081.gif',
  'Barbell reverse wrist curl': 'lib/edb-0082.gif',
  'Barbell seated behind head military press': 'lib/edb-0086.gif',
  'Barbell seated bradford rocky press': 'lib/edb-0087.gif',
  'Barbell seated calf raise': 'lib/edb-0088.gif',
  'Barbell seated close grip behind neck triceps extension': 'lib/edb-1718.gif',
  'Barbell seated close-grip concentration curl': 'lib/edb-0089.gif',
  'Barbell seated good morning': 'lib/edb-0090.gif',
  'Barbell seated overhead triceps extension': 'lib/edb-0092.gif',
  'Barbell seated twist': 'lib/edb-0094.gif',
  'Barbell side split squat': 'lib/edb-0098.gif',
  'Barbell single leg deadlift': 'lib/edb-1756.gif',
  'Barbell single leg split squat': 'lib/edb-0099.gif',
  'Barbell sitted alternate leg raise': 'lib/edb-2799.gif',
  'Barbell skier': 'lib/edb-0100.gif',
  'Barbell speed squat': 'lib/edb-0101.gif',
  'Barbell split squat (version 2)': 'lib/edb-2809.gif',
  'Barbell squat (on knees)': 'lib/edb-0102.gif',
  'Barbell squat jump step rear lunge': 'lib/edb-2797.gif',
  'Barbell standing back wrist curl': 'lib/edb-0104.gif',
  'Barbell standing bradford press': 'lib/edb-0105.gif',
  'Barbell standing close grip curl': 'lib/edb-0106.gif',
  'Barbell standing close grip military press': 'lib/edb-1456.gif',
  'Barbell standing concentration curl': 'lib/edb-2414.gif',
  'Barbell standing front raise over head': 'lib/edb-0107.gif',
  'Barbell standing leg calf raise': 'lib/edb-0108.gif',
  'Barbell standing overhead triceps extension': 'lib/edb-0109.gif',
  'Barbell standing reverse grip curl': 'lib/edb-0110.gif',
  'Barbell standing rocking leg calf raise': 'lib/edb-0111.gif',
  'Barbell standing twist': 'lib/edb-0112.gif',
  'Barbell standing wide grip biceps curl': 'lib/edb-1629.gif',
  'Barbell standing wide military press': 'lib/edb-1457.gif',
  'Barbell standing wide-grip curl': 'lib/edb-0113.gif',
  'Barbell stiff leg good morning': 'lib/edb-0115.gif',
  'Barbell straight leg deadlift': 'lib/edb-0116.gif',
  'Barbell weightlifting complex': 'lib/edb-3316.gif',
  'Barbell wide bench press': 'lib/edb-0122.gif',
  'Barbell wide reverse grip bench press': 'lib/edb-1258.gif',
  'Barbell wide squat': 'lib/edb-0124.gif',
  'Barbell wide-grip upright row': 'lib/edb-0123.gif',
  'Barbell zercher squat': 'lib/edb-0127.gif',
  'Bench dip (knees bent)': 'lib/edb-0129.gif',
  'Bench dip on floor': 'lib/edb-1399.gif',
  'Bench hip extension': 'lib/edb-0130.gif',
  'Bench pull-ups': 'lib/edb-3019.gif',
  'Biceps leg concentration curl': 'lib/edb-1770.gif',
  'Biceps narrow pull-ups': 'lib/edb-0139.gif',
  'Biceps pull-up': 'lib/edb-0140.gif',
  'Body-up': 'lib/edb-0137.gif',
  'Bodyweight drop jump squat': 'lib/edb-3543.gif',
  'Bodyweight kneeling triceps extension': 'lib/edb-1771.gif',
  'Bodyweight side lying biceps curl': 'lib/edb-1769.gif',
  'Bodyweight squatting row': 'lib/edb-3168.gif',
  'Bodyweight standing calf raise': 'lib/edb-1373.gif',
  'Bodyweight standing close-grip one arm row': 'lib/edb-3156.gif',
  'Bodyweight standing close-grip row': 'lib/edb-3158.gif',
  'Bodyweight standing one arm row': 'lib/edb-3162.gif',
  'Bodyweight standing row': 'lib/edb-3166.gif',
  'Bottoms-up': 'lib/edb-0138.gif',
  'Box jump down with one leg stabilization': 'lib/edb-1374.gif',
  'Boxing jab': 'lib/edb-2272.gif',
  'Boxing left uppercut': 'lib/edb-2275.gif',
  'Bridge - mountain climber (cross body)': 'lib/edb-2466.gif',
  'Broad jump to vertical': 'lib/edb-4242.gif',
  'Butt-ups': 'lib/edb-0870.gif',
  'Butterfly yoga pose': 'lib/edb-1494.gif',
  'Cable alternate shoulder press': 'lib/edb-0148.gif',
  'Cable alternate triceps extension': 'lib/edb-0149.gif',
  'Cable bar lateral pulldown': 'lib/edb-0150.gif',
  'Cable bench press': 'lib/edb-0151.gif',
  'Cable close grip curl': 'lib/edb-1630.gif',
  'Cable concentration curl': 'lib/edb-1631.gif',
  'Cable concentration extension (on knee)': 'lib/edb-0152.gif',
  'Cable cross-over lateral pulldown': 'lib/edb-0153.gif',
  'Cable cross-over reverse fly': 'lib/edb-0154.gif',
  'Cable cross-over variation': 'lib/edb-0155.gif',
  'Cable deadlift': 'lib/edb-0157.gif',
  'Cable decline fly': 'lib/edb-0158.gif',
  'Cable decline one arm press': 'lib/edb-1260.gif',
  'Cable decline press': 'lib/edb-1261.gif',
  'Cable decline seated wide-grip row': 'lib/edb-0159.gif',
  'Cable drag curl': 'lib/edb-1632.gif',
  'Cable floor seated wide-grip row': 'lib/edb-0160.gif',
  'Cable forward raise': 'lib/edb-0161.gif',
  'Cable front shoulder raise': 'lib/edb-0164.gif',
  'Cable high pulley overhead tricep extension': 'lib/edb-1722.gif',
  'Cable high row (kneeling)': 'lib/edb-0167.gif',
  'Cable hip adduction': 'lib/edb-0168.gif',
  'Cable incline bench press': 'lib/edb-0169.gif',
  'Cable incline bench row': 'lib/edb-1318.gif',
  'Cable incline pushdown': 'lib/edb-0172.gif',
  'Cable incline triceps extension': 'lib/edb-0173.gif',
  'Cable judo flip': 'lib/edb-0174.gif',
  'Cable kneeling triceps extension': 'lib/edb-0176.gif',
  'Cable lat pulldown full range of motion': 'lib/edb-2330.gif',
  'Cable lateral pulldown (with rope attachment)': 'lib/edb-0177.gif',
  'Cable low fly': 'lib/edb-0179.gif',
  'Cable low seated row': 'lib/edb-0180.gif',
  'Cable lying bicep curl': 'lib/edb-1634.gif',
  'Cable lying close-grip curl': 'lib/edb-0182.gif',
  'Cable lying fly': 'lib/edb-0185.gif',
  'Cable middle fly': 'lib/edb-0188.gif',
  'Cable one arm decline chest fly': 'lib/edb-1262.gif',
  'Cable one arm incline press': 'lib/edb-1265.gif',
  'Cable one arm lateral bent-over': 'lib/edb-0191.gif',
  'Cable one arm lateral raise': 'lib/edb-0192.gif',
  'Cable one arm preacher curl': 'lib/edb-1633.gif',
  'Cable one arm pulldown': 'lib/edb-3563.gif',
  'Cable one arm reverse preacher curl': 'lib/edb-1635.gif',
  'Cable one arm straight back high row (kneeling)': 'lib/edb-0193.gif',
  'Cable one arm tricep pushdown': 'lib/edb-1723.gif',
  'Cable overhead curl': 'lib/edb-1636.gif',
  'Cable palm rotational row': 'lib/edb-1319.gif',
  'Cable preacher curl': 'lib/edb-0195.gif',
  'Cable pulldown (pro lat bar)': 'lib/edb-0197.gif',
  'Cable pulldown bicep curl': 'lib/edb-1638.gif',
  'Cable rear delt row (stirrups)': 'lib/edb-0202.gif',
  'Cable rear delt row (with rope)': 'lib/edb-0203.gif',
  'Cable rear drive': 'lib/edb-0204.gif',
  'Cable reverse crunch': 'lib/edb-0873.gif',
  'Cable reverse curl': 'lib/edb-0206.gif',
  'Cable reverse grip triceps pushdown (sz-bar) (with arm blaster)': 'lib/edb-2406.gif',
  'Cable reverse one arm curl': 'lib/edb-1413.gif',
  'Cable reverse preacher curl': 'lib/edb-0209.gif',
  'Cable reverse wrist curl': 'lib/edb-0210.gif',
  'Cable reverse-grip pushdown': 'lib/edb-0207.gif',
  'Cable reverse-grip straight back seated high row': 'lib/edb-0208.gif',
  'Cable rope crossover seated row': 'lib/edb-1320.gif',
  'Cable rope elevated seated row': 'lib/edb-1321.gif',
  'Cable rope extension incline bench row': 'lib/edb-1322.gif',
  'Cable rope hammer preacher curl': 'lib/edb-1639.gif',
  'Cable rope high pulley overhead tricep extension': 'lib/edb-1724.gif',
  'Cable rope incline tricep extension': 'lib/edb-1725.gif',
  'Cable rope lying on floor tricep extension': 'lib/edb-1726.gif',
  'Cable rope one arm hammer preacher curl': 'lib/edb-1640.gif',
  'Cable rope seated row': 'lib/edb-1323.gif',
  'Cable seated crunch': 'lib/edb-0212.gif',
  'Cable seated curl': 'lib/edb-1641.gif',
  'Cable seated high row (v-bar)': 'lib/edb-0213.gif',
  'Cable seated neck extension (with head harness)': 'lib/edb-2411.gif',
  'Cable seated neck flexion (with head harness)': 'lib/edb-2412.gif',
  'Cable seated one arm alternate row': 'lib/edb-0214.gif',
  'Cable seated one arm concentration curl': 'lib/edb-1642.gif',
  'Cable seated overhead curl': 'lib/edb-1643.gif',
  'Cable seated shoulder internal rotation': 'lib/edb-0216.gif',
  'Cable seated twist': 'lib/edb-2399.gif',
  'Cable seated wide-grip row': 'lib/edb-0218.gif',
  'Cable shoulder press': 'lib/edb-0219.gif',
  'Cable shrug': 'lib/edb-0220.gif',
  'Cable side bend': 'lib/edb-0222.gif',
  'Cable side crunch': 'lib/edb-0223.gif',
  'Cable squat row (with rope attachment)': 'lib/edb-1717.gif',
  'Cable squatting curl': 'lib/edb-1644.gif',
  'Cable standing back wrist curl': 'lib/edb-0224.gif',
  'Cable standing calf raise': 'lib/edb-1375.gif',
  'Cable standing cross-over high reverse fly': 'lib/edb-0225.gif',
  'Cable standing crunch': 'lib/edb-0226.gif',
  'Cable standing crunch (with rope attachment)': 'lib/edb-0874.gif',
  'Cable standing hip extension': 'lib/edb-0228.gif',
  'Cable standing inner curl': 'lib/edb-0229.gif',
  'Cable standing lift': 'lib/edb-0230.gif',
  'Cable standing one arm triceps extension': 'lib/edb-0231.gif',
  'Cable standing one leg calf raise': 'lib/edb-1376.gif',
  'Cable standing pulldown (with rope)': 'lib/edb-0232.gif',
  'Cable standing reverse grip one arm overhead tricep extension': 'lib/edb-1727.gif',
  'Cable standing row (v-bar)': 'lib/edb-0234.gif',
  'Cable standing shoulder external rotation': 'lib/edb-0235.gif',
  'Cable standing twist row (v-bar)': 'lib/edb-0236.gif',
  'Cable straight arm pulldown (with rope)': 'lib/edb-0237.gif',
  'Cable straight back seated row': 'lib/edb-0239.gif',
  'Cable supine reverse fly': 'lib/edb-0240.gif',
  'Cable thibaudeau kayak row': 'lib/edb-2464.gif',
  'Cable triceps pushdown (v-bar)': 'lib/edb-0241.gif',
  'Cable triceps pushdown (v-bar) (with arm blaster)': 'lib/edb-2405.gif',
  'Cable tuck reverse crunch': 'lib/edb-0242.gif',
  'Cable twist (up-down)': 'lib/edb-0862.gif',
  'Cable twisting pull': 'lib/edb-0244.gif',
  'Cable two arm curl on incline bench': 'lib/edb-1645.gif',
  'Cable two arm tricep kickback': 'lib/edb-1728.gif',
  'Cable underhand pulldown': 'lib/edb-0245.gif',
  'Cable upper chest crossovers': 'lib/edb-1270.gif',
  'Cable upright row': 'lib/edb-0246.gif',
  'Cable wide grip rear pulldown behind neck': 'lib/edb-1325.gif',
  'Cable wrist curl': 'lib/edb-0247.gif',
  'Calf push stretch with hands against wall': 'lib/edb-1407.gif',
  'Calf stretch with hands against wall': 'lib/edb-1377.gif',
  'Cambered bar lying row': 'lib/edb-0248.gif',
  'Captains chair straight leg raise': 'lib/edb-2963.gif',
  'Chair leg extended stretch': 'lib/edb-1548.gif',
  'Chest and front of shoulder stretch': 'lib/edb-1271.gif',
  'Chest dip (on dip-pull-up cage)': 'lib/edb-1430.gif',
  'Chest dip on straight bar': 'lib/edb-2462.gif',
  'Chin tuck': 'lib/edb-3149.gif',
  'Chin-ups (narrow parallel grip)': 'lib/edb-0253.gif',
  'Circles knee stretch': 'lib/edb-0257.gif',
  'Clap push up': 'lib/edb-1273.gif',
  'Clock push-up': 'lib/edb-0258.gif',
  'Close grip chin-up': 'lib/edb-1327.gif',
  'Close-grip push-up': 'lib/edb-0259.gif',
  'Close-grip push-up (on knees)': 'lib/edb-2398.gif',
  'Cocoons': 'lib/edb-0260.gif',
  'Crab twist toe touch': 'lib/edb-1468.gif',
  'Cross body crunch': 'lib/edb-0262.gif',
  'Crunch (hands overhead)': 'lib/edb-0267.gif',
  'Curl-up': 'lib/edb-3016.gif',
  'Curtsey squat': 'lib/edb-3769.gif',
  'Dead bug': 'lib/edb-0276.gif',
  'Decline crunch': 'lib/edb-0277.gif',
  'Decline push-up': 'lib/edb-0279.gif',
  'Decline sit-up': 'lib/edb-0282.gif',
  'Diamond push-up': 'lib/edb-0283.gif',
  'Donkey calf raise': 'lib/edb-0284.gif',
  'Drop push up': 'lib/edb-1275.gif',
  'Dumbbell alternate biceps curl': 'lib/edb-0285.gif',
  'Dumbbell alternate biceps curl (with arm blaster)': 'lib/edb-2403.gif',
  'Dumbbell alternate hammer preacher curl': 'lib/edb-1646.gif',
  'Dumbbell alternate preacher curl': 'lib/edb-1647.gif',
  'Dumbbell alternate seated hammer curl': 'lib/edb-1648.gif',
  'Dumbbell alternate side press': 'lib/edb-0286.gif',
  'Dumbbell around pullover': 'lib/edb-0288.gif',
  'Dumbbell bench seated press': 'lib/edb-0290.gif',
  'Dumbbell bench squat': 'lib/edb-0291.gif',
  'Dumbbell bent over row': 'lib/edb-0293.gif',
  'Dumbbell bicep curl lunge with bowling motion': 'lib/edb-1651.gif',
  'Dumbbell bicep curl with stork stance': 'lib/edb-1653.gif',
  'Dumbbell biceps curl (with arm blaster)': 'lib/edb-2401.gif',
  'Dumbbell biceps curl reverse': 'lib/edb-1654.gif',
  'Dumbbell biceps curl squat': 'lib/edb-1655.gif',
  'Dumbbell clean': 'lib/edb-0295.gif',
  'Dumbbell close grip press': 'lib/edb-1731.gif',
  'Dumbbell close-grip press': 'lib/edb-0296.gif',
  'Dumbbell complex push up row clean and press': 'lib/edb-3886.gif',
  'Dumbbell contralateral forward lunge': 'lib/edb-3635.gif',
  'Dumbbell cross body hammer curl': 'lib/edb-0298.gif',
  'Dumbbell cuban press': 'lib/edb-0299.gif',
  'Dumbbell deadlift': 'lib/edb-0300.gif',
  'Dumbbell decline bench press': 'lib/edb-0301.gif',
  'Dumbbell decline fly': 'lib/edb-0302.gif',
  'Dumbbell decline hammer press': 'lib/edb-0303.gif',
  'Dumbbell decline one arm fly': 'lib/edb-1276.gif',
  'Dumbbell decline one arm hammer press': 'lib/edb-1617.gif',
  'Dumbbell decline shrug': 'lib/edb-0305.gif',
  'Dumbbell decline triceps extension': 'lib/edb-0306.gif',
  'Dumbbell decline twist fly': 'lib/edb-0307.gif',
  'Dumbbell finger curls': 'lib/edb-1437.gif',
  'Dumbbell forward lunge triceps extension': 'lib/edb-1732.gif',
  'Dumbbell full can lateral raise': 'lib/edb-0311.gif',
  'Dumbbell hammer curls (with arm blaster)': 'lib/edb-2402.gif',
  'Dumbbell high curl': 'lib/edb-1664.gif',
  'Dumbbell incline alternate press': 'lib/edb-3545.gif',
  'Dumbbell incline biceps curl': 'lib/edb-0315.gif',
  'Dumbbell incline breeding': 'lib/edb-0316.gif',
  'Dumbbell incline curl': 'lib/edb-0318.gif',
  'Dumbbell incline fly': 'lib/edb-0319.gif',
  'Dumbbell incline hammer curl': 'lib/edb-0320.gif',
  'Dumbbell incline hammer press': 'lib/edb-0321.gif',
  'Dumbbell incline inner biceps curl': 'lib/edb-0322.gif',
  'Dumbbell incline one arm fly': 'lib/edb-1279.gif',
  'Dumbbell incline one arm hammer press': 'lib/edb-1619.gif',
  'Dumbbell incline one arm lateral raise': 'lib/edb-0323.gif',
  'Dumbbell incline one arm press': 'lib/edb-1281.gif',
  'Dumbbell incline palm-in press': 'lib/edb-0324.gif',
  'Dumbbell incline raise': 'lib/edb-0325.gif',
  'Dumbbell incline rear lateral raise': 'lib/edb-0326.gif',
  'Dumbbell incline row': 'lib/edb-0327.gif',
  'Dumbbell incline shoulder raise': 'lib/edb-0328.gif',
  'Dumbbell incline shrug': 'lib/edb-0329.gif',
  'Dumbbell incline t-raise': 'lib/edb-3542.gif',
  'Dumbbell incline triceps extension': 'lib/edb-0330.gif',
  'Dumbbell incline twisted flyes': 'lib/edb-0331.gif',
  'Dumbbell incline two arm extension': 'lib/edb-1733.gif',
  'Dumbbell incline y-raise': 'lib/edb-3541.gif',
  'Dumbbell iron cross': 'lib/edb-0332.gif',
  'Dumbbell lateral to front raise': 'lib/edb-0335.gif',
  'Dumbbell lunge with bicep curl': 'lib/edb-1658.gif',
  'Dumbbell lying alternate extension': 'lib/edb-1729.gif',
  'Dumbbell lying elbow press': 'lib/edb-0338.gif',
  'Dumbbell lying extension (across face)': 'lib/edb-0337.gif',
  'Dumbbell lying external shoulder rotation': 'lib/edb-0863.gif',
  'Dumbbell lying femoral': 'lib/edb-0339.gif',
  'Dumbbell lying hammer press': 'lib/edb-0340.gif',
  'Dumbbell lying on floor rear delt raise': 'lib/edb-2470.gif',
  'Dumbbell lying one arm deltoid rear': 'lib/edb-0341.gif',
  'Dumbbell lying one arm press': 'lib/edb-0343.gif',
  'Dumbbell lying one arm pronated triceps extension': 'lib/edb-0344.gif',
  'Dumbbell lying one arm rear lateral raise': 'lib/edb-0345.gif',
  'Dumbbell lying one arm supinated triceps extension': 'lib/edb-0346.gif',
  'Dumbbell lying pronation': 'lib/edb-0347.gif',
  'Dumbbell lying pronation on floor': 'lib/edb-2705.gif',
  'Dumbbell lying rear delt row': 'lib/edb-1328.gif',
  'Dumbbell lying rear lateral raise': 'lib/edb-0348.gif',
  'Dumbbell lying single extension': 'lib/edb-1735.gif',
  'Dumbbell lying supination': 'lib/edb-0349.gif',
  'Dumbbell lying supination on floor': 'lib/edb-2706.gif',
  'Dumbbell lying supine biceps curl': 'lib/edb-1661.gif',
  'Dumbbell lying supine curl': 'lib/edb-0350.gif',
  'Dumbbell lying triceps extension': 'lib/edb-0351.gif',
  'Dumbbell lying wide curl': 'lib/edb-1662.gif',
  'Dumbbell neutral grip bench press': 'lib/edb-0352.gif',
  'Dumbbell one arm bench fly': 'lib/edb-1285.gif',
  'Dumbbell one arm decline chest press': 'lib/edb-1287.gif',
  'Dumbbell one arm hammer preacher curl': 'lib/edb-1663.gif',
  'Dumbbell one arm incline chest press': 'lib/edb-1289.gif',
  'Dumbbell one arm kickback': 'lib/edb-0354.gif',
  'Dumbbell one arm lateral raise': 'lib/edb-0355.gif',
  'Dumbbell one arm lateral raise with support': 'lib/edb-0356.gif',
  'Dumbbell one arm prone curl': 'lib/edb-1665.gif',
  'Dumbbell one arm prone hammer curl': 'lib/edb-1666.gif',
  'Dumbbell one arm reverse fly (with support)': 'lib/edb-0359.gif',
  'Dumbbell one arm reverse grip press': 'lib/edb-1622.gif',
  'Dumbbell one arm reverse preacher curl': 'lib/edb-1414.gif',
  'Dumbbell one arm reverse spider curl': 'lib/edb-1667.gif',
  'Dumbbell one arm reverse wrist curl': 'lib/edb-0358.gif',
  'Dumbbell one arm seated hammer curl': 'lib/edb-1669.gif',
  'Dumbbell one arm seated neutral wrist curl': 'lib/edb-1415.gif',
  'Dumbbell one arm shoulder press': 'lib/edb-0361.gif',
  'Dumbbell one arm snatch': 'lib/edb-3888.gif',
  'Dumbbell one arm standing curl': 'lib/edb-1670.gif',
  'Dumbbell one arm standing hammer curl': 'lib/edb-1671.gif',
  'Dumbbell one arm triceps extension (on bench)': 'lib/edb-0362.gif',
  'Dumbbell one arm upright row': 'lib/edb-0363.gif',
  'Dumbbell one arm wrist curl': 'lib/edb-0364.gif',
  'Dumbbell one arm zottman preacher curl': 'lib/edb-1672.gif',
  'Dumbbell over bench neutral wrist curl': 'lib/edb-0365.gif',
  'Dumbbell over bench one arm neutral wrist curl': 'lib/edb-0366.gif',
  'Dumbbell over bench one arm reverse wrist curl': 'lib/edb-1441.gif',
  'Dumbbell over bench one arm wrist curl': 'lib/edb-0367.gif',
  'Dumbbell over bench reverse wrist curl': 'lib/edb-0368.gif',
  'Dumbbell over bench wrist curl': 'lib/edb-0369.gif',
  'Dumbbell palm rotational bent over row': 'lib/edb-1329.gif',
  'Dumbbell palms in incline bench press': 'lib/edb-1623.gif',
  'Dumbbell plyo squat': 'lib/edb-0371.gif',
  'Dumbbell preacher curl': 'lib/edb-0372.gif',
  'Dumbbell preacher hammer curl': 'lib/edb-0370.gif',
  'Dumbbell pronate-grip triceps extension': 'lib/edb-0373.gif',
  'Dumbbell prone incline curl': 'lib/edb-0374.gif',
  'Dumbbell prone incline hammer curl': 'lib/edb-1674.gif',
  'Dumbbell pullover': 'lib/edb-0375.gif',
  'Dumbbell raise': 'lib/edb-0376.gif',
  'Dumbbell rear delt raise': 'lib/edb-2292.gif',
  'Dumbbell rear delt row (shoulder)': 'lib/edb-0377.gif',
  'Dumbbell rear fly': 'lib/edb-0378.gif',
  'Dumbbell rear lateral raise (support head)': 'lib/edb-0379.gif',
  'Dumbbell rear lunge': 'lib/edb-0381.gif',
  'Dumbbell reverse bench press': 'lib/edb-1624.gif',
  'Dumbbell reverse grip biceps curl': 'lib/edb-0382.gif',
  'Dumbbell reverse grip incline bench one arm row': 'lib/edb-1330.gif',
  'Dumbbell reverse grip incline bench two arm row': 'lib/edb-1331.gif',
  'Dumbbell reverse preacher curl': 'lib/edb-0384.gif',
  'Dumbbell reverse spider curl': 'lib/edb-1675.gif',
  'Dumbbell reverse wrist curl': 'lib/edb-0385.gif',
  'Dumbbell romanian deadlift': 'lib/edb-1459.gif',
  'Dumbbell rotation reverse fly': 'lib/edb-0386.gif',
  'Dumbbell scott press': 'lib/edb-2397.gif',
  'Dumbbell seated alternate front raise': 'lib/edb-0387.gif',
  'Dumbbell seated alternate press': 'lib/edb-0388.gif',
  'Dumbbell seated alternate shoulder': 'lib/edb-3546.gif',
  'Dumbbell seated bench extension': 'lib/edb-0389.gif',
  'Dumbbell seated bent arm lateral raise': 'lib/edb-2317.gif',
  'Dumbbell seated bent over alternate kickback': 'lib/edb-1730.gif',
  'Dumbbell seated bent over triceps extension': 'lib/edb-1737.gif',
  'Dumbbell seated bicep curl': 'lib/edb-1677.gif',
  'Dumbbell seated biceps curl to shoulder press': 'lib/edb-3547.gif',
  'Dumbbell seated calf raise': 'lib/edb-1379.gif',
  'Dumbbell seated curl': 'lib/edb-0391.gif',
  'Dumbbell seated front raise': 'lib/edb-0392.gif',
  'Dumbbell seated hammer curl': 'lib/edb-1678.gif',
  'Dumbbell seated inner biceps curl': 'lib/edb-0393.gif',
  'Dumbbell seated kickback': 'lib/edb-0394.gif',
  'Dumbbell seated lateral raise': 'lib/edb-0396.gif',
  'Dumbbell seated neutral wrist curl': 'lib/edb-0397.gif',
  'Dumbbell seated one arm kickback': 'lib/edb-0398.gif',
  'Dumbbell seated one arm rotate': 'lib/edb-0399.gif',
  'Dumbbell seated one leg calf raise': 'lib/edb-0400.gif',
  'Dumbbell seated one leg calf raise - hammer grip': 'lib/edb-1380.gif',
  'Dumbbell seated one leg calf raise - palm up': 'lib/edb-1381.gif',
  'Dumbbell seated palms up wrist curl': 'lib/edb-0401.gif',
  'Dumbbell seated preacher curl': 'lib/edb-0402.gif',
  'Dumbbell seated reverse grip concentration curl': 'lib/edb-0403.gif',
  'Dumbbell seated reverse grip one arm overhead tricep extension': 'lib/edb-1738.gif',
  'Dumbbell seated shoulder press (parallel grip)': 'lib/edb-0404.gif',
  'Dumbbell seated triceps extension': 'lib/edb-2188.gif',
  'Dumbbell side bend': 'lib/edb-0407.gif',
  'Dumbbell side lying one hand raise': 'lib/edb-0408.gif',
  'Dumbbell side plank with rear fly': 'lib/edb-3664.gif',
  'Dumbbell single arm overhead carry': 'lib/edb-3548.gif',
  'Dumbbell single leg calf raise': 'lib/edb-0409.gif',
  'Dumbbell single leg deadlift': 'lib/edb-1757.gif',
  'Dumbbell single leg deadlift with stepbox support': 'lib/edb-2806.gif',
  'Dumbbell single leg split squat': 'lib/edb-0410.gif',
  'Dumbbell single leg squat': 'lib/edb-0411.gif',
  'Dumbbell squat': 'lib/edb-0413.gif',
  'Dumbbell standing alternate hammer curl and press': 'lib/edb-3560.gif',
  'Dumbbell standing alternate overhead press': 'lib/edb-0414.gif',
  'Dumbbell standing alternate raise': 'lib/edb-0415.gif',
  'Dumbbell standing alternating tricep kickback': 'lib/edb-1739.gif',
  'Dumbbell standing around world': 'lib/edb-2143.gif',
  'Dumbbell standing bent over one arm triceps extension': 'lib/edb-1740.gif',
  'Dumbbell standing bent over two arm triceps extension': 'lib/edb-1741.gif',
  'Dumbbell standing biceps curl': 'lib/edb-0416.gif',
  'Dumbbell standing calf raise': 'lib/edb-0417.gif',
  'Dumbbell standing concentration curl': 'lib/edb-0418.gif',
  'Dumbbell standing front raise above head': 'lib/edb-0419.gif',
  'Dumbbell standing kickback': 'lib/edb-0420.gif',
  'Dumbbell standing one arm concentration curl': 'lib/edb-0421.gif',
  'Dumbbell standing one arm curl (over incline bench)': 'lib/edb-0422.gif',
  'Dumbbell standing one arm curl over incline bench': 'lib/edb-1680.gif',
  'Dumbbell standing one arm extension': 'lib/edb-0423.gif',
  'Dumbbell standing one arm palm in press': 'lib/edb-0424.gif',
  'Dumbbell standing one arm reverse curl': 'lib/edb-0425.gif',
  'Dumbbell standing overhead press': 'lib/edb-0426.gif',
  'Dumbbell standing palms in press': 'lib/edb-0427.gif',
  'Dumbbell standing preacher curl': 'lib/edb-0428.gif',
  'Dumbbell standing reverse curl': 'lib/edb-0429.gif',
  'Dumbbell standing triceps extension': 'lib/edb-0430.gif',
  'Dumbbell standing zottman preacher curl': 'lib/edb-2293.gif',
  'Dumbbell step up lunge': 'lib/edb-2795.gif',
  'Dumbbell step up single leg balance with bicep curl': 'lib/edb-1684.gif',
  'Dumbbell step-up': 'lib/edb-0431.gif',
  'Dumbbell step-up lunge': 'lib/edb-2796.gif',
  'Dumbbell step-up split squat': 'lib/edb-2812.gif',
  'Dumbbell stiff leg deadlift': 'lib/edb-0432.gif',
  'Dumbbell straight arm pullover': 'lib/edb-0433.gif',
  'Dumbbell straight leg deadlift': 'lib/edb-0434.gif',
  'Dumbbell sumo pull through': 'lib/edb-2807.gif',
  'Dumbbell supported squat': 'lib/edb-2804.gif',
  'Dumbbell tate press': 'lib/edb-0436.gif',
  'Dumbbell tricep kickback with stork stance': 'lib/edb-1742.gif',
  'Dumbbell twisting bench press': 'lib/edb-1743.gif',
  'Dumbbell upright row': 'lib/edb-0437.gif',
  'Dumbbell upright shoulder external rotation': 'lib/edb-0864.gif',
  'Dumbbell w-press': 'lib/edb-0438.gif',
  'Dumbbell waiter biceps curl': 'lib/edb-5201.gif',
  'Dumbbell zottman curl': 'lib/edb-0439.gif',
  'Dumbbell zottman preacher curl': 'lib/edb-2294.gif',
  'Dumbbells seated triceps extension': 'lib/edb-2189.gif',
  'Elbow dips': 'lib/edb-3287.gif',
  'Elbow lift - reverse push-up': 'lib/edb-1772.gif',
  'Elbow-to-knee': 'lib/edb-0443.gif',
  'Elevator': 'lib/edb-3292.gif',
  'Ez bar lying bent arms pullover': 'lib/edb-3010.gif',
  'Ez bar lying close grip triceps extension behind head': 'lib/edb-1748.gif',
  'Ez bar reverse grip bent over row': 'lib/edb-1344.gif',
  'Ez bar seated close grip concentration curl': 'lib/edb-1682.gif',
  'Ez bar standing french press': 'lib/edb-1749.gif',
  'Ez barbell anti gravity press': 'lib/edb-0445.gif',
  'Ez barbell close grip preacher curl': 'lib/edb-1627.gif',
  'Ez barbell close-grip curl': 'lib/edb-0446.gif',
  'Ez barbell curl': 'lib/edb-0447.gif',
  'Ez barbell decline close grip face press': 'lib/edb-0448.gif',
  'Ez barbell decline triceps extension': 'lib/edb-2186.gif',
  'Ez barbell incline triceps extension': 'lib/edb-0449.gif',
  'Ez barbell jm bench press': 'lib/edb-0450.gif',
  'Ez barbell reverse grip curl': 'lib/edb-0451.gif',
  'Ez barbell reverse grip preacher curl': 'lib/edb-0452.gif',
  'Ez barbell seated curls': 'lib/edb-1458.gif',
  'Ez barbell seated triceps extension': 'lib/edb-0453.gif',
  'Ez barbell spider curl': 'lib/edb-1628.gif',
  'Ez-bar biceps curl (with arm blaster)': 'lib/edb-2404.gif',
  'Ez-bar close-grip bench press': 'lib/edb-2432.gif',
  'Ez-barbell standing wide grip biceps curl': 'lib/edb-2741.gif',
  'Finger curls': 'lib/edb-0455.gif',
  'Flexion leg sit up (bent knee)': 'lib/edb-0456.gif',
  'Flexion leg sit up (straight arm)': 'lib/edb-0457.gif',
  'Floor fly (with barbell)': 'lib/edb-0458.gif',
  'Flutter kicks': 'lib/edb-0459.gif',
  'Forward jump': 'lib/edb-1472.gif',
  'Frankenstein squat': 'lib/edb-3194.gif',
  'Frog crunch': 'lib/edb-2429.gif',
  'Frog planche': 'lib/edb-3301.gif',
  'Front and back neck stretch': 'lib/edb-0462.gif',
  'Front groin kick': 'lib/edb-2303.gif',
  'Front leg hook kick': 'lib/edb-2302.gif',
  'Front lever': 'lib/edb-3296.gif',
  'Front lever reps': 'lib/edb-3295.gif',
  'Front plank with twist': 'lib/edb-0464.gif',
  'Front snap kick': 'lib/edb-2305.gif',
  'Full maltese': 'lib/edb-3315.gif',
  'Full planche': 'lib/edb-3299.gif',
  'Full planche push-up': 'lib/edb-3327.gif',
  'Gironda sternum chin': 'lib/edb-0466.gif',
  'Glute bridge march': 'lib/edb-3561.gif',
  'Glute-ham raise': 'lib/edb-3193.gif',
  'Gorilla chin': 'lib/edb-0467.gif',
  'Groin crunch': 'lib/edb-0469.gif',
  'Hamstring stretch': 'lib/edb-1511.gif',
  'Handstand': 'lib/edb-3302.gif',
  'Handstand push-up': 'lib/edb-0471.gif',
  'Hanging leg hip raise': 'lib/edb-1764.gif',
  'Hanging oblique knee raise': 'lib/edb-1761.gif',
  'Hanging pike': 'lib/edb-0473.gif',
  'Hanging straight leg hip raise': 'lib/edb-0474.gif',
  'Hanging straight leg raise': 'lib/edb-0475.gif',
  'Hanging straight twisting leg hip raise': 'lib/edb-0476.gif',
  'Heel push kick': 'lib/edb-2309.gif',
  'Hip raise (bent knee)': 'lib/edb-0484.gif',
  'Hug knees to chest': 'lib/edb-1418.gif',
  'Hyght dumbbell fly': 'lib/edb-3234.gif',
  'Hyperextension (on bench)': 'lib/edb-0488.gif',
  'Impossible dips': 'lib/edb-3289.gif',
  'Inchworm': 'lib/edb-1471.gif',
  'Incline close-grip push-up': 'lib/edb-0490.gif',
  'Incline leg hip raise (leg straight)': 'lib/edb-0491.gif',
  'Incline push up depth jump': 'lib/edb-0492.gif',
  'Incline push-up': 'lib/edb-0493.gif',
  'Incline push-up (on box)': 'lib/edb-3785.gif',
  'Incline reverse grip push-up': 'lib/edb-0494.gif',
  'Incline scapula push up': 'lib/edb-3011.gif',
  'Incline twisting sit-up': 'lib/edb-0495.gif',
  'Inverse leg curl (bench support)': 'lib/edb-0496.gif',
  'Inverted row': 'lib/edb-0499.gif',
  'Inverted row bent knees': 'lib/edb-2300.gif',
  'Inverted row on bench': 'lib/edb-2298.gif',
  'Inverted row with straps': 'lib/edb-0498.gif',
  'Iron cross stretch': 'lib/edb-1419.gif',
  'Isometric chest squeeze': 'lib/edb-1297.gif',
  'Isometric wipers': 'lib/edb-0500.gif',
  'Jackknife sit-up': 'lib/edb-0507.gif',
  'Janda sit-up': 'lib/edb-0508.gif',
  'Jump squat': 'lib/edb-0514.gif',
  'Kettlebell advanced windmill': 'lib/edb-0517.gif',
  'Kettlebell alternating hang clean': 'lib/edb-0518.gif',
  'Kettlebell alternating press': 'lib/edb-0520.gif',
  'Kettlebell alternating press on floor': 'lib/edb-0519.gif',
  'Kettlebell alternating renegade row': 'lib/edb-0521.gif',
  'Kettlebell alternating row': 'lib/edb-0522.gif',
  'Kettlebell arnold press': 'lib/edb-0523.gif',
  'Kettlebell bent press': 'lib/edb-0524.gif',
  'Kettlebell bottoms up clean from the hang position': 'lib/edb-0525.gif',
  'Kettlebell double alternating hang clean': 'lib/edb-0526.gif',
  'Kettlebell double jerk': 'lib/edb-0527.gif',
  'Kettlebell double push press': 'lib/edb-0528.gif',
  'Kettlebell double snatch': 'lib/edb-0529.gif',
  'Kettlebell double windmill': 'lib/edb-0530.gif',
  'Kettlebell extended range one arm press on floor': 'lib/edb-0531.gif',
  'Kettlebell figure 8': 'lib/edb-0532.gif',
  'Kettlebell front squat': 'lib/edb-0533.gif',
  'Kettlebell goblet squat': 'lib/edb-0534.gif',
  'Kettlebell hang clean': 'lib/edb-0535.gif',
  'Kettlebell lunge pass through': 'lib/edb-0536.gif',
  'Kettlebell one arm clean and jerk': 'lib/edb-0537.gif',
  'Kettlebell one arm floor press': 'lib/edb-1298.gif',
  'Kettlebell one arm jerk': 'lib/edb-0538.gif',
  'Kettlebell one arm military press to the side': 'lib/edb-0539.gif',
  'Kettlebell one arm push press': 'lib/edb-0540.gif',
  'Kettlebell one arm row': 'lib/edb-0541.gif',
  'Kettlebell one arm snatch': 'lib/edb-0542.gif',
  'Kettlebell overhead carry': 'lib/edb-4244.gif',
  'Kettlebell pirate supper legs': 'lib/edb-0543.gif',
  'Kettlebell plyo push-up': 'lib/edb-0545.gif',
  'Kettlebell seated press': 'lib/edb-0546.gif',
  'Kettlebell seated two arm military press': 'lib/edb-1438.gif',
  'Kettlebell seesaw press': 'lib/edb-0547.gif',
  'Kettlebell sumo high pull': 'lib/edb-0548.gif',
  'Kettlebell thruster': 'lib/edb-0550.gif',
  'Kettlebell turkish get up (squat style)': 'lib/edb-0551.gif',
  'Kettlebell two arm clean': 'lib/edb-0552.gif',
  'Kettlebell two arm military press': 'lib/edb-0553.gif',
  'Kettlebell two arm row': 'lib/edb-1345.gif',
  'Kettlebell windmill': 'lib/edb-0554.gif',
  'Kick out sit': 'lib/edb-0555.gif',
  'Kipping muscle up': 'lib/edb-0558.gif',
  'Knee touch crunch': 'lib/edb-3640.gif',
  'Kneeling jump squat': 'lib/edb-1420.gif',
  'Kneeling lat stretch': 'lib/edb-1346.gif',
  'Korean dips': 'lib/edb-3288.gif',
  'L-pull-up': 'lib/edb-3418.gif',
  'L-sit on floor': 'lib/edb-3419.gif',
  'Landmine 180': 'lib/edb-0562.gif',
  'Landmine lateral raise': 'lib/edb-3237.gif',
  'Lean planche': 'lib/edb-3300.gif',
  'Left hook (boxing)': 'lib/edb-2271.gif',
  'Leg pull in flat bench': 'lib/edb-0570.gif',
  'Leg up hamstring stretch': 'lib/edb-1576.gif',
  'Lever alternate leg press': 'lib/edb-2287.gif',
  'Lever alternating narrow grip seated row': 'lib/edb-0571.gif',
  'Lever back extension': 'lib/edb-0573.gif',
  'Lever bent over row': 'lib/edb-0574.gif',
  'Lever bent-over row with v-bar': 'lib/edb-3200.gif',
  'Lever bicep curl': 'lib/edb-0575.gif',
  'Lever calf press': 'lib/edb-2289.gif',
  'Lever chest press': 'lib/edb-0576.gif',
  'Lever deadlift': 'lib/edb-0578.gif',
  'Lever decline chest press': 'lib/edb-1300.gif',
  'Lever donkey calf raise': 'lib/edb-1253.gif',
  'Lever front pulldown': 'lib/edb-0579.gif',
  'Lever gripless shrug': 'lib/edb-0580.gif',
  'Lever gripper hands': 'lib/edb-2288.gif',
  'Lever hammer grip preacher curl': 'lib/edb-1615.gif',
  'Lever high row': 'lib/edb-0581.gif',
  'Lever horizontal one leg press': 'lib/edb-2611.gif',
  'Lever incline chest press': 'lib/edb-1299.gif',
  'Lever kneeling leg curl': 'lib/edb-0582.gif',
  'Lever kneeling twist': 'lib/edb-0583.gif',
  'Lever lateral raise': 'lib/edb-0584.gif',
  'Lever lying two-one leg curl': 'lib/edb-3195.gif',
  'Lever military press': 'lib/edb-0587.gif',
  'Lever narrow grip seated row': 'lib/edb-0588.gif',
  'Lever neck extension (plate loaded)': 'lib/edb-2282.gif',
  'Lever neck left side flexion (plate loaded)': 'lib/edb-2283.gif',
  'Lever neck right side flexion (plate loaded)': 'lib/edb-2284.gif',
  'Lever one arm bent over row': 'lib/edb-0589.gif',
  'Lever one arm lateral high row': 'lib/edb-1356.gif',
  'Lever one arm lateral wide pulldown': 'lib/edb-1347.gif',
  'Lever one arm shoulder press': 'lib/edb-0590.gif',
  'Lever overhand triceps dip': 'lib/edb-0591.gif',
  'Lever preacher curl': 'lib/edb-0592.gif',
  'Lever pullover': 'lib/edb-2285.gif',
  'Lever reverse grip lateral pulldown': 'lib/edb-2736.gif',
  'Lever reverse grip preacher curl': 'lib/edb-1616.gif',
  'Lever reverse grip vertical row': 'lib/edb-1348.gif',
  'Lever reverse hyperextension': 'lib/edb-0593.gif',
  'Lever reverse t-bar row': 'lib/edb-1349.gif',
  'Lever rotary calf': 'lib/edb-2315.gif',
  'Lever seated calf press': 'lib/edb-2335.gif',
  'Lever seated calf raise': 'lib/edb-0594.gif',
  'Lever seated crunch': 'lib/edb-1452.gif',
  'Lever seated crunch (chest pad)': 'lib/edb-0595.gif',
  'Lever seated dip': 'lib/edb-1451.gif',
  'Lever seated good morning': 'lib/edb-3759.gif',
  'Lever seated hip adduction': 'lib/edb-0598.gif',
  'Lever seated leg raise crunch': 'lib/edb-0600.gif',
  'Lever seated reverse fly': 'lib/edb-0602.gif',
  'Lever seated reverse fly (parallel grip)': 'lib/edb-0601.gif',
  'Lever seated row': 'lib/edb-1350.gif',
  'Lever seated squat calf raise on leg press machine': 'lib/edb-1385.gif',
  'Lever shrug': 'lib/edb-0604.gif',
  'Lever standing calf raise': 'lib/edb-0605.gif',
  'Lever standing chest press': 'lib/edb-3758.gif',
  'Lever t-bar reverse grip row': 'lib/edb-1351.gif',
  'Lever triceps extension': 'lib/edb-0607.gif',
  'Lever unilateral row': 'lib/edb-1313.gif',
  'Low glute bridge on floor': 'lib/edb-3013.gif',
  'Lower back curl': 'lib/edb-1352.gif',
  'Lunge with jump': 'lib/edb-3582.gif',
  'Lunge with twist': 'lib/edb-1688.gif',
  'Lying (side) quads stretch': 'lib/edb-0613.gif',
  'Lying elbow to knee': 'lib/edb-2312.gif',
  'Lying leg-hip raise': 'lib/edb-0865.gif',
  'Machine inner chest press': 'lib/edb-1301.gif',
  'March sit (wall)': 'lib/edb-0624.gif',
  'Mixed grip chin-up': 'lib/edb-0627.gif',
  'Modified push up to lower arms': 'lib/edb-1421.gif',
  'Muscle up': 'lib/edb-0631.gif',
  'Muscle-up (on vertical bar)': 'lib/edb-1401.gif',
  'Neck bridge prone': 'lib/edb-0633.gif',
  'Neck side stretch': 'lib/edb-1403.gif',
  'Negative crunch': 'lib/edb-0634.gif',
  'Oblique crunches floor': 'lib/edb-0635.gif',
  'Olympic barbell hammer curl': 'lib/edb-0636.gif',
  'Olympic barbell triceps extension': 'lib/edb-0637.gif',
  'One arm against wall': 'lib/edb-1355.gif',
  'One arm chin-up': 'lib/edb-0638.gif',
  'One arm dip': 'lib/edb-0639.gif',
  'One leg donkey calf raise': 'lib/edb-1386.gif',
  'One leg floor calf raise': 'lib/edb-1387.gif',
  'One leg squat': 'lib/edb-1476.gif',
  'Otis up': 'lib/edb-0641.gif',
  'Outside leg kick push-up': 'lib/edb-0642.gif',
  'Overhead triceps stretch': 'lib/edb-0643.gif',
  'Pelvic tilt': 'lib/edb-3147.gif',
  'Pelvic tilt into bridge': 'lib/edb-1422.gif',
  'Pike-to-cobra push-up': 'lib/edb-3662.gif',
  'Plyo push up': 'lib/edb-1306.gif',
  'Posterior step to overhead reach': 'lib/edb-1687.gif',
  'Potty squat': 'lib/edb-3119.gif',
  'Potty squat with support': 'lib/edb-3132.gif',
  'Power point plank': 'lib/edb-3665.gif',
  'Prancing': 'lib/edb-3197.gif',
  'Pull up (neutral grip)': 'lib/edb-0651.gif',
  'Push and pull bodyweight': 'lib/edb-1689.gif',
  'Push-up (wall)': 'lib/edb-0659.gif',
  'Push-up close-grip off dumbbell': 'lib/edb-0660.gif',
  'Push-up inside leg kick': 'lib/edb-0661.gif',
  'Push-up on lower arms': 'lib/edb-1467.gif',
  'Push-up plus': 'lib/edb-3145.gif',
  'Push-up to side plank': 'lib/edb-0664.gif',
  'Quads (bodyweight squat)': 'lib/edb-3533.gif',
  'Quarter sit-up': 'lib/edb-3201.gif',
  'Raise single arm push-up': 'lib/edb-0666.gif',
  'Rear axe kick': 'lib/edb-2304.gif',
  'Rear decline bridge': 'lib/edb-0668.gif',
  'Rear deltoid stretch': 'lib/edb-0669.gif',
  'Rear leg hook kick': 'lib/edb-2301.gif',
  'Rear pull-up': 'lib/edb-0670.gif',
  'Reverse crunch': 'lib/edb-0872.gif',
  'Reverse dip': 'lib/edb-0672.gif',
  'Reverse grip machine lat pulldown': 'lib/edb-0673.gif',
  'Reverse grip pull-up': 'lib/edb-0674.gif',
  'Reverse hyper on flat bench': 'lib/edb-1423.gif',
  'Reverse plank with leg lift': 'lib/edb-3663.gif',
  'Ring dips': 'lib/edb-0677.gif',
  'Rocking frog stretch': 'lib/edb-2571.gif',
  'Rocky pull-up pulldown': 'lib/edb-0678.gif',
  'Roll overs into v sits': 'lib/edb-2572.gif',
  'Roundhouse kick': 'lib/edb-2308.gif',
  'Runners stretch': 'lib/edb-1585.gif',
  'Scapula dips': 'lib/edb-3012.gif',
  'Scapula push-up': 'lib/edb-3021.gif',
  'Scapular pull-up': 'lib/edb-0688.gif',
  'Seated glute stretch': 'lib/edb-1424.gif',
  'Seated leg raise': 'lib/edb-0689.gif',
  'Seated lower back stretch': 'lib/edb-0690.gif',
  'Seated piriformis stretch': 'lib/edb-2567.gif',
  'Seated side crunch (wall)': 'lib/edb-0691.gif',
  'Seated wide angle pose sequence': 'lib/edb-1587.gif',
  'Shoulder grip pull-up': 'lib/edb-1763.gif',
  'Shoulder tap': 'lib/edb-3699.gif',
  'Shoulder tap push-up': 'lib/edb-0699.gif',
  'Side bridge hip abduction': 'lib/edb-1774.gif',
  'Side hip (on parallel bars)': 'lib/edb-0709.gif',
  'Side hip abduction': 'lib/edb-0710.gif',
  'Side kick': 'lib/edb-2307.gif',
  'Side lying floor stretch': 'lib/edb-1358.gif',
  'Side neck stretch': 'lib/edb-0713.gif',
  'Side plank hip adduction': 'lib/edb-1775.gif',
  'Side push neck stretch': 'lib/edb-0716.gif',
  'Side push-up': 'lib/edb-0717.gif',
  'Side wrist pull stretch': 'lib/edb-0721.gif',
  'Side-to-side chin': 'lib/edb-0720.gif',
  'Single arm push-up': 'lib/edb-0725.gif',
  'Single leg board jump': 'lib/edb-4245.gif',
  'Single leg bridge with outstretched leg': 'lib/edb-3645.gif',
  'Single leg calf raise (on a dumbbell)': 'lib/edb-0727.gif',
  'Single leg platform slide': 'lib/edb-0730.gif',
  'Single leg squat (pistol) male': 'lib/edb-1759.gif',
  'Single leg vertical jump': 'lib/edb-4254.gif',
  'Sissy squat': 'lib/edb-1489.gif',
  'Sit-up with arms on chest': 'lib/edb-3679.gif',
  'Skin the cat': 'lib/edb-3304.gif',
  'Smith back shrug': 'lib/edb-0746.gif',
  'Smith behind neck press': 'lib/edb-0747.gif',
  'Smith bench press': 'lib/edb-0748.gif',
  'Smith bent knee good morning': 'lib/edb-0749.gif',
  'Smith bent over row': 'lib/edb-1359.gif',
  'Smith chair squat': 'lib/edb-0750.gif',
  'Smith close-grip bench press': 'lib/edb-0751.gif',
  'Smith deadlift': 'lib/edb-0752.gif',
  'Smith decline bench press': 'lib/edb-0753.gif',
  'Smith decline reverse-grip press': 'lib/edb-0754.gif',
  'Smith front squat (clean grip)': 'lib/edb-1433.gif',
  'Smith full squat': 'lib/edb-3281.gif',
  'Smith hack squat': 'lib/edb-0755.gif',
  'Smith hip raise': 'lib/edb-0756.gif',
  'Smith incline bench press': 'lib/edb-0757.gif',
  'Smith incline reverse-grip press': 'lib/edb-0758.gif',
  'Smith incline shoulder raises': 'lib/edb-0759.gif',
  'Smith leg press': 'lib/edb-0760.gif',
  'Smith low bar squat': 'lib/edb-1434.gif',
  'Smith machine bicep curl': 'lib/edb-1683.gif',
  'Smith machine decline close grip bench press': 'lib/edb-1625.gif',
  'Smith machine incline tricep extension': 'lib/edb-1752.gif',
  'Smith machine reverse decline close grip bench press': 'lib/edb-1626.gif',
  'Smith narrow row': 'lib/edb-0761.gif',
  'Smith one arm row': 'lib/edb-1360.gif',
  'Smith one leg floor calf raise': 'lib/edb-1393.gif',
  'Smith rear delt row': 'lib/edb-0762.gif',
  'Smith reverse calf raises': 'lib/edb-1394.gif',
  'Smith reverse grip bent over row': 'lib/edb-1361.gif',
  'Smith reverse-grip press': 'lib/edb-0764.gif',
  'Smith seated one leg calf raise': 'lib/edb-1395.gif',
  'Smith seated shoulder press': 'lib/edb-0765.gif',
  'Smith seated wrist curl': 'lib/edb-1426.gif',
  'Smith shoulder press': 'lib/edb-0766.gif',
  'Smith shrug': 'lib/edb-0767.gif',
  'Smith single leg split squat': 'lib/edb-0768.gif',
  'Smith sprint lunge': 'lib/edb-0769.gif',
  'Smith squat': 'lib/edb-0770.gif',
  'Smith standing back wrist curl': 'lib/edb-0771.gif',
  'Smith standing behind head military press': 'lib/edb-0772.gif',
  'Smith standing leg calf raise': 'lib/edb-0773.gif',
  'Smith standing military press': 'lib/edb-0774.gif',
  'Smith sumo squat': 'lib/edb-3142.gif',
  'Smith toe raise': 'lib/edb-1396.gif',
  'Smith upright row': 'lib/edb-0775.gif',
  'Smith wide grip bench press': 'lib/edb-1308.gif',
  'Smith wide grip decline bench press': 'lib/edb-1309.gif',
  'Snatch pull': 'lib/edb-0776.gif',
  'Spell caster': 'lib/edb-0777.gif',
  'Sphinx': 'lib/edb-1362.gif',
  'Spider crawl push up': 'lib/edb-0778.gif',
  'Spin back kick': 'lib/edb-2310.gif',
  'Spin hook kick': 'lib/edb-2306.gif',
  'Spine stretch': 'lib/edb-1363.gif',
  'Spine twist': 'lib/edb-2329.gif',
  'Squat jerk': 'lib/edb-0786.gif',
  'Squat to overhead reach': 'lib/edb-1685.gif',
  'Squat to overhead reach with twist': 'lib/edb-1686.gif',
  'Stalder press': 'lib/edb-3291.gif',
  'Standing archer': 'lib/edb-3669.gif',
  'Standing behind neck press': 'lib/edb-0788.gif',
  'Standing calf raise (on a staircase)': 'lib/edb-1490.gif',
  'Standing calves': 'lib/edb-1397.gif',
  'Standing calves calf stretch': 'lib/edb-1398.gif',
  'Standing lateral stretch': 'lib/edb-0794.gif',
  'Standing pelvic tilt': 'lib/edb-1364.gif',
  'Standing single leg curl': 'lib/edb-0795.gif',
  'Stepdown squat': 'lib/edb-4256.gif',
  'Straddle maltese': 'lib/edb-3314.gif',
  'Straddle planche': 'lib/edb-3298.gif',
  'Straight leg hip bridge': 'lib/edb-4255.gif',
  'Straight leg outer hip abductor': 'lib/edb-1427.gif',
  'Strongman fingal\'s fingers': 'lib/edb-3306.gif',
  'Strongman keg toss': 'lib/edb-3307.gif',
  'Superman push-up': 'lib/edb-0803.gif',
  'Three bench dip': 'lib/edb-1753.gif',
  'Toe touch sit (wall)': 'lib/edb-0810.gif',
  'Trap bar deadlift': 'lib/edb-0811.gif',
  'Triceps dip': 'lib/edb-0814.gif',
  'Triceps dip (bench leg)': 'lib/edb-0812.gif',
  'Triceps dip (between benches)': 'lib/edb-0813.gif',
  'Triceps dips floor': 'lib/edb-0815.gif',
  'Triceps press': 'lib/edb-0816.gif',
  'Triceps stretch': 'lib/edb-0817.gif',
  'Tuck crunch': 'lib/edb-0871.gif',
  'Twin handle parallel grip lat pulldown': 'lib/edb-0818.gif',
  'Twist hip lift': 'lib/edb-1466.gif',
  'Twisted leg raise': 'lib/edb-2802.gif',
  'Upper back stretch': 'lib/edb-1365.gif',
  'Upward facing dog': 'lib/edb-1366.gif',
  'V-sit on floor': 'lib/edb-3420.gif',
  'Vertical leg raise (on parallel bars)': 'lib/edb-0826.gif',
  'Walking lunge': 'lib/edb-1460.gif',
  'Weighted bench dip': 'lib/edb-0830.gif',
  'Weighted close grip chin-up on dip cage': 'lib/edb-2987.gif',
  'Weighted crunch': 'lib/edb-0832.gif',
  'Weighted crunch (behind head)': 'lib/edb-1250.gif',
  'Weighted decline sit-up': 'lib/edb-3670.gif',
  'Weighted donkey calf raise': 'lib/edb-0833.gif',
  'Weighted drop push up': 'lib/edb-1310.gif',
  'Weighted front raise': 'lib/edb-0834.gif',
  'Weighted hanging leg-hip raise': 'lib/edb-0866.gif',
  'Weighted kneeling step with swing': 'lib/edb-3641.gif',
  'Weighted lunge with swing': 'lib/edb-3644.gif',
  'Weighted lying neck extension (with head harness)': 'lib/edb-2408.gif',
  'Weighted lying neck flexion (with head harness)': 'lib/edb-2409.gif',
  'Weighted lying side lifting head (with head harness)': 'lib/edb-0838.gif',
  'Weighted muscle up': 'lib/edb-3286.gif',
  'Weighted muscle up (on bar)': 'lib/edb-3312.gif',
  'Weighted one hand pull up': 'lib/edb-3290.gif',
  'Weighted pull-up': 'lib/edb-0841.gif',
  'Weighted round arm': 'lib/edb-0844.gif',
  'Weighted russian twist': 'lib/edb-0846.gif',
  'Weighted russian twist (legs up)': 'lib/edb-0845.gif',
  'Weighted seated neck extension (with head harness)': 'lib/edb-0848.gif',
  'Weighted sissy squat': 'lib/edb-0851.gif',
  'Weighted squat': 'lib/edb-0852.gif',
  'Weighted standing curl': 'lib/edb-0853.gif',
  'Weighted standing hand squeeze': 'lib/edb-0854.gif',
  'Weighted standing neck extension (with head harness)': 'lib/edb-2410.gif',
  'Weighted straight bar dip': 'lib/edb-3313.gif',
  'Weighted stretch lunge': 'lib/edb-3642.gif',
  'Weighted svend press': 'lib/edb-0856.gif',
  'Weighted three bench dips': 'lib/edb-1754.gif',
  'Weighted tricep dips': 'lib/edb-1755.gif',
  'Weighted triceps dip on high parallel bars': 'lib/edb-1767.gif',
  'Wide grip pull-up': 'lib/edb-1429.gif',
  'Wide grip rear pull-up': 'lib/edb-1367.gif',
  'Wide hand push up': 'lib/edb-1311.gif',
  'Wide-grip chest dip on high parallel bars': 'lib/edb-2363.gif',
  'Wind sprints': 'lib/edb-0858.gif',
  'World greatest stretch': 'lib/edb-1604.gif',
  'Wrist circles': 'lib/edb-1428.gif',
  'Zigzag hops': 'lib/edb-3198.gif',
}

/** Publik URL till valfri fil i övningsbucketen, utan supabase-klienten:
    flödesytorna renderas även i miljöer (tester) där klienten inte finns. */
export function publicExerciseImageUrl(path: string): string | null {
  const base = process.env.EXPO_PUBLIC_SUPABASE_URL
  return base ? `${base}/storage/v1/object/public/exercise-images/${path}` : null
}

export function exerciseImageFor(name: string): string | null {
  return EXERCISE_IMAGES[name] ?? null
}

export function exerciseImageUrlFor(name: string): string | null {
  const file = EXERCISE_IMAGES[name]
  return file ? publicExerciseImageUrl(file) : null
}

/** Stillbild (första bildrutan) — listor ska inte myllra av animationer */
export function exerciseStillUrlFor(name: string): string | null {
  const file = EXERCISE_IMAGES[name]
  return file ? publicExerciseImageUrl(`still/${file.replace(/\.gif$/, '.png')}`) : null
}
