import type { ExerciseInfo } from './types'

// Genererad från det licensierade ExerciseDB-paketet. Svenska steg är
// manuellt översatta, engelska är originalen.
export const PART_2: Record<string, ExerciseInfo> = {
  'Front squat': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Framsida lår', 'Baksida lår', 'Vader', 'Bål'],
    steps: [
      { sv: 'Börja med att stå med fötterna axelbrett isär och tårna lätt utåtvridna.', en: 'Start by standing with your feet shoulder-width apart, toes slightly turned out.' },
      { sv: 'Håll skivstången framför axlarna, vilande mot nyckelbenen och axlarna.', en: 'Hold the barbell in front of your shoulders, resting it on your collarbone and shoulders.' },
      { sv: 'Spänn bålen och håll bröstet uppåt medan du sänker dig ner i en knäböj genom att skjuta höfterna bakåt och böja knäna.', en: 'Engage your core and keep your chest up as you lower your body down into a squat position, pushing your hips back and bending your knees.' },
      { sv: 'Sänk dig tills låren är parallella med golvet, eller så djupt som känns bekvämt.', en: 'Lower until your thighs are parallel to the ground, or as low as you can comfortably go.' },
      { sv: 'Pausa ett ögonblick i botten och pressa sedan genom hälarna för att återgå till startpositionen.', en: 'Pause for a moment at the bottom, then push through your heels to return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Frontlyft': {
    equipment: 'Hantlar',
    target: 'Axlar',
    secondary: ['Biceps', 'Trapezius'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand med handflatorna mot låren.', en: 'Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.' },
      { sv: 'Håll armarna raka, andas ut och lyft hantlarna framför dig tills de är i axelhöjd.', en: 'Keeping your arms straight, exhale and lift the dumbbells in front of you until they are at shoulder level.' },
      { sv: 'Pausa ett ögonblick i toppen, andas sedan in och sänk långsamt hantlarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Frontlyft i kabel': {
    equipment: 'Kabel',
    target: 'Axlar',
    secondary: ['Triceps', 'Underarmar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och greppa kabelhandtaget med överhandsgrepp.', en: 'Stand with your feet shoulder-width apart and grasp the cable handle with an overhand grip.' },
      { sv: 'Håll ryggen rak och bålen spänd.', en: 'Keep your back straight and your core engaged.' },
      { sv: 'Lyft kabelhandtaget framför dig med raka armar och handflatorna nedåt.', en: 'Raise the cable handle in front of you, keeping your arms straight and your palms facing down.' },
      { sv: 'Fortsätt lyfta tills armarna är parallella med golvet.', en: 'Continue lifting until your arms are parallel to the floor.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt kabelhandtaget tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the cable handle back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Genomdrag med kabel': {
    equipment: 'Kabel',
    target: 'Säte',
    secondary: ['Baksida lår', 'Nedre rygg'],
    steps: [
      { sv: 'Stå med ryggen mot kabelmaskinen med fötterna axelbrett isär.', en: 'Stand facing away from the cable machine with your feet shoulder-width apart.' },
      { sv: 'Greppa repet med båda händerna och ta ett steg framåt så att kabeln spänns.', en: 'Grab the rope attachment with both hands and step forward, creating tension in the cable.' },
      { sv: 'Fäll i höften och sänk överkroppen tills den är parallell med golvet, med rak rygg.', en: 'Bend at the hips and lower your upper body until it is parallel to the ground, keeping your back straight.' },
      { sv: 'Aktivera säte och baksida lår för att dra dig upp till startpositionen igen.', en: 'Engage your glutes and hamstrings to pull your body back up to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Glute kickback i kabel': {
    equipment: 'Kabel',
    target: 'Triceps',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Stå vänd mot en kabelmaskin med fötterna axelbrett isär.', en: 'Stand facing a cable machine with your feet shoulder-width apart.' },
      { sv: 'Håll kabelhandtaget med höger hand och ta ett steg bakåt så att kabeln spänns.', en: 'Hold the cable handle with your right hand and step back to create tension in the cable.' },
      { sv: 'Böj knäna lätt och fäll överkroppen framåt i höften med rak rygg.', en: 'Bend your knees slightly and hinge forward at the hips, keeping your back straight.' },
      { sv: 'Håll överarmen nära kroppen med armbågen böjd i 90 grader.', en: 'Keep your upper arm close to your body and your elbow bent at a 90-degree angle.' },
      { sv: 'Sträck underarmen bakåt tills armen är helt rak.', en: 'Extend your forearm backward, straightening your arm fully.' },
      { sv: 'Pausa ett ögonblick och återgå sedan långsamt till startpositionen.', en: 'Pause for a moment, then slowly return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner och byt sedan sida.', en: 'Repeat for the desired number of repetitions, then switch sides.' },
    ],
  },
  'Goblet squat': {
    equipment: 'Hantlar',
    target: 'Framsida lår',
    secondary: ['Säte', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel lodrätt mot bröstet med båda händerna.', en: 'Stand with your feet shoulder-width apart, holding a dumbbell vertically against your chest with both hands.' },
      { sv: 'Håll bröstet uppåt och bålen spänd medan du sänker dig ner i en knäböj genom att skjuta höfterna bakåt och böja knäna.', en: 'Keeping your chest up and core engaged, lower your body down into a squat position by pushing your hips back and bending your knees.' },
      { sv: 'Fortsätt nedåt tills låren är parallella med golvet, eller så djupt som känns bekvämt.', en: 'Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.' },
      { sv: 'Pausa ett ögonblick i botten och pressa sedan genom hälarna för att återgå till startpositionen.', en: 'Pause for a moment at the bottom, then push through your heels to return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Good mornings': {
    equipment: 'Skivstång',
    target: 'Baksida lår',
    secondary: ['Nedre rygg'],
    steps: [
      { sv: 'Börja med att stå med fötterna axelbrett isär och skivstången vilande på övre delen av ryggen.', en: 'Start by standing with your feet shoulder-width apart and the barbell resting on your upper back.' },
      { sv: 'Håll ryggen rak och bålen spänd, fäll framåt i höften och skjut rumpan bakåt som om du försökte nudda väggen bakom dig med sätet.', en: 'Keeping your back straight and your core engaged, hinge forward at the hips, pushing your buttocks back as if you were trying to touch the wall behind you with your glutes.' },
      { sv: 'Sänk överkroppen tills den är parallell med golvet och känn hur det sträcker i baksida lår.', en: 'Lower your torso until it is parallel to the ground, feeling a stretch in your hamstrings.' },
      { sv: 'Pausa ett ögonblick och återgå sedan till startpositionen genom att spänna sätet och pressa höfterna framåt.', en: 'Pause for a moment, then return to the starting position by squeezing your glutes and pushing your hips forward.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hack squat': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Framsida lår', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Börja med att stå med fötterna axelbrett isär och tårna lätt utåtvridna.', en: 'Start by standing with your feet shoulder-width apart and your toes slightly turned out.' },
      { sv: 'Håll skivstången bakom benen, vilande mot övre delen av låren.', en: 'Hold the barbell behind your legs, resting it on your upper thighs.' },
      { sv: 'Sänk kroppen genom att böja i knän och höfter, med rak rygg och bröstet uppåt.', en: 'Lower your body by bending at the knees and hips, keeping your back straight and your chest up.' },
      { sv: 'Fortsätt nedåt tills låren är parallella med golvet, eller så djupt som känns bekvämt.', en: 'Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.' },
      { sv: 'Pausa ett ögonblick och pressa sedan genom hälarna för att återgå till startpositionen.', en: 'Pause for a moment, then push through your heels to return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hammercurl': {
    equipment: 'Hantlar',
    target: 'Biceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Stå upprätt med en hantel i varje hand och handflatorna vända mot kroppen.', en: 'Stand up straight with a dumbbell in each hand, palms facing your torso.' },
      { sv: 'Håll armbågarna nära kroppen och vrid handflatorna tills de pekar framåt.', en: 'Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.' },
      { sv: 'Detta är din startposition.', en: 'This will be your starting position.' },
      { sv: 'Håll överarmarna stilla, andas ut och curla vikterna medan du spänner biceps.', en: 'Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.' },
      { sv: 'Fortsätt lyfta vikterna tills biceps är helt kontraherade och hantlarna är i axelhöjd.', en: 'Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.' },
      { sv: 'Håll den spända positionen en kort stund medan du kniper åt i biceps.', en: 'Hold the contracted position for a brief pause as you squeeze your biceps.' },
      { sv: 'Andas sedan in och börja långsamt sänka hantlarna tillbaka till startpositionen.', en: 'Then, inhale and slowly begin to lower the dumbbells back to the starting position.' },
      { sv: 'Upprepa rekommenderat antal repetitioner.', en: 'Repeat for the recommended amount of repetitions.' },
    ],
  },
  'Handledscurl': {
    equipment: 'Skivstång',
    target: 'Underarmar',
    secondary: ['Biceps', 'Brachialis'],
    steps: [
      { sv: 'Sitt på en bänk med fötterna i golvet och underarmarna vilande på låren, och håll en skivstång med underhandsgrepp.', en: 'Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, holding a barbell with an underhand grip.' },
      { sv: 'Låt skivstången rulla ner mot fingertopparna och håll handlederna raka.', en: 'Allow the barbell to roll down to your fingertips, keeping your wrists straight.' },
      { sv: 'Curla långsamt upp skivstången mot underarmarna genom att böja i handlederna.', en: 'Slowly curl the barbell up towards your forearms by flexing your wrists.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt skivstången tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the barbell back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hantelpress axlar': {
    equipment: 'Hantlar',
    target: 'Axlar',
    secondary: ['Triceps', 'Övre rygg'],
    steps: [
      { sv: 'Sitt på en bänk med en hantel i varje hand, vilande på låren.', en: 'Sit on a bench with a dumbbell in each hand, resting on your thighs.' },
      { sv: 'Lyft hantlarna till axelhöjd med handflatorna framåt.', en: 'Raise the dumbbells to shoulder height, palms facing forward.' },
      { sv: 'Pressa hantlarna uppåt tills armarna är helt utsträckta ovanför huvudet.', en: 'Press the dumbbells upward until your arms are fully extended overhead.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt hantlarna tillbaka till axelhöjd.', en: 'Pause for a moment at the top, then slowly lower the dumbbells back to shoulder height.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hantelpress liggande': {
    equipment: 'Hantlar',
    target: 'Bröst',
    secondary: ['Triceps', 'Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med fötterna i golvet och ryggen pressad mot bänken.', en: 'Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.' },
      { sv: 'Håll en hantel i varje hand med handflatorna framåt och armarna utsträckta ovanför bröstet.', en: 'Hold a dumbbell in each hand, with your palms facing forward and your arms extended above your chest.' },
      { sv: 'Sänk hantlarna långsamt mot bröstets sidor och håll armbågarna i 90 graders vinkel.', en: 'Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.' },
      { sv: 'Pausa ett ögonblick och pressa sedan upp hantlarna till startpositionen med helt utsträckta armar.', en: 'Pause for a moment, then push the dumbbells back up to the starting position, fully extending your arms.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hip thrust': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Baksida lår', 'Bål'],
    steps: [
      { sv: 'Börja med att sitta vid kanten av en bänk med övre delen av ryggen mot bänken och fötterna i golvet, höftbrett isär.', en: 'Start by sitting on the edge of a bench with your upper back resting against it and your feet flat on the ground, hip-width apart.' },
      { sv: 'Placera en skivstång över höfterna och håll den stadigt med båda händerna.', en: 'Place a barbell across your hips, holding it securely with both hands.' },
      { sv: 'Spänn säte och bål och pressa sedan genom hälarna för att lyfta höfterna från bänken, så att kroppen bildar en rak linje från knän till axlar.', en: 'Engage your glutes and core muscles, then press through your heels to lift your hips off the bench, creating a straight line from your knees to your shoulders.' },
      { sv: 'Pausa ett ögonblick i toppen och knip åt i sätet.', en: 'Pause for a moment at the top, squeezing your glutes.' },
      { sv: 'Sänk långsamt höfterna tillbaka till startpositionen.', en: 'Slowly lower your hips back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hyperextensions': {
    equipment: 'Ingen utrustning',
    target: 'Nedre rygg',
    secondary: ['Säte', 'Baksida lår'],
    steps: [
      { sv: 'Ställ in ryggresarbänken så att övre delen av låren vilar på dynan och fötterna sitter fast.', en: 'Adjust the hyperextension bench so that your upper thighs are resting on the pad and your feet are secured.' },
      { sv: 'Korsa armarna över bröstet eller placera händerna bakom huvudet.', en: 'Cross your arms over your chest or place your hands behind your head.' },
      { sv: 'Sänk överkroppen mot golvet med rak rygg.', en: 'Lower your upper body towards the ground while keeping your back straight.' },
      { sv: 'Pausa ett ögonblick i botten och lyft sedan överkroppen tills den är i linje med benen.', en: 'Pause for a moment at the bottom, then raise your upper body back up until it is in line with your legs.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Hängande benlyft': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Höftböjare'],
    steps: [
      { sv: 'Häng i en chinsstång med helt utsträckta armar och handflatorna vända bort från dig.', en: 'Hang from a pull-up bar with your arms fully extended and your palms facing away from you.' },
      { sv: 'Spänn bålen och lyft benen framför dig, håll dem raka.', en: 'Engage your core and lift your legs up in front of you, keeping them straight.' },
      { sv: 'Fortsätt lyfta tills benen är parallella med golvet eller så högt som känns bekvämt.', en: 'Continue lifting until your legs are parallel to the ground or as high as you can comfortably go.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt benen tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your legs back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Höftabduktion i kabel': {
    equipment: 'Maskin',
    target: 'Abduktorer',
    secondary: ['Säte', 'Baksida lår'],
    steps: [
      { sv: 'Ställ in sitshöjden så att knäna är i 90 graders vinkel.', en: 'Adjust the seat height so that your knees are at a 90-degree angle.' },
      { sv: 'Sitt i maskinen med ryggen mot ryggstödet och fötterna på fotstöden.', en: 'Sit on the machine with your back against the backrest and your feet on the footrests.' },
      { sv: 'Placera händerna på sidohandtagen för stabilitet.', en: 'Place your hands on the side handles for stability.' },
      { sv: 'Aktivera abduktorerna och pressa långsamt isär benen, bort från kroppens mittlinje.', en: 'Engage your abductors and slowly push your legs apart, away from the midline of your body.' },
      { sv: 'Pausa ett ögonblick i slutet av rörelsen och för sedan långsamt ihop benen till startpositionen igen.', en: 'Pause for a moment at the end of the movement, then slowly bring your legs back together to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelbiceps': {
    equipment: 'Kabel',
    target: 'Biceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Stå vänd mot kabelmaskinen med fötterna axelbrett isär.', en: 'Stand facing the cable machine with your feet shoulder-width apart.' },
      { sv: 'Greppa kabelhandtaget med underhandsgrepp och handflatorna uppåt.', en: 'Grasp the cable attachment with an underhand grip, palms facing up.' },
      { sv: 'Håll armbågarna nära sidorna och överarmarna stilla.', en: 'Keep your elbows close to your sides and your upper arms stationary.' },
      { sv: 'Andas ut och curla handtaget mot axlarna medan du spänner biceps.', en: 'Exhale and curl the cable attachment towards your shoulders, contracting your biceps.' },
      { sv: 'Pausa ett ögonblick i toppen av rörelsen och knip åt i biceps.', en: 'Pause for a moment at the top of the movement, squeezing your biceps.' },
      { sv: 'Andas in och sänk långsamt handtaget tillbaka till startpositionen.', en: 'Inhale and slowly lower the cable attachment back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelcrunch': {
    equipment: 'Kabel',
    target: 'Magmuskler',
    secondary: ['Sneda magmuskler'],
    steps: [
      { sv: 'Fäst ett rephandtag i ett högt block och gå ner på knä vänd bort från maskinen.', en: 'Attach a rope handle to a high pulley and kneel down facing away from the machine.' },
      { sv: 'Håll repet med båda händerna och placera det bakom huvudet med armbågarna utåt sidorna.', en: 'Hold the rope handle with both hands and place it behind your head, keeping your elbows out to the sides.' },
      { sv: 'Håll höfterna stilla, böj i midjan och pressa överkroppen ner mot låren.', en: 'Keeping your hips stationary, flex your waist and crunch your torso down towards your thighs.' },
      { sv: 'Pausa ett ögonblick i botten och återgå sedan långsamt till startpositionen.', en: 'Pause for a moment at the bottom, then slowly return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelcurl med rep': {
    equipment: 'Kabel',
    target: 'Biceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Stå upprätt med fötterna axelbrett isär och lätt böjda knän.', en: 'Stand upright with your feet shoulder-width apart and a slight bend in your knees.' },
      { sv: 'Håll repet med underhandsgrepp, handflatorna mot varandra och armarna helt utsträckta.', en: 'Hold the cable rope attachment with an underhand grip, palms facing each other, and your arms fully extended.' },
      { sv: 'Håll överarmarna stilla, andas ut och curla vikten medan du spänner biceps.', en: 'Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.' },
      { sv: 'Fortsätt lyfta repet tills biceps är helt kontraherade och repet är i axelhöjd.', en: 'Continue to raise the cable rope attachment until your biceps are fully contracted and the rope is at shoulder level.' },
      { sv: 'Håll den spända positionen en kort stund medan du kniper åt i biceps.', en: 'Hold the contracted position for a brief pause as you squeeze your biceps.' },
      { sv: 'Andas in och börja långsamt sänka repet tillbaka till startpositionen.', en: 'Inhale and slowly begin to lower the cable rope attachment back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelflyes': {
    equipment: 'Kabel',
    target: 'Bröst',
    secondary: ['Axlar', 'Triceps'],
    steps: [
      { sv: 'Fäst handtagen i kablarna i brösthöjd.', en: 'Attach the handles to the cables at chest height.' },
      { sv: 'Stå med fötterna axelbrett isär, vänd bort från kabelmaskinen.', en: 'Stand with your feet shoulder-width apart, facing away from the cable machine.' },
      { sv: 'Greppa handtagen med överhandsgrepp och handflatorna framåt.', en: 'Grasp the handles with an overhand grip, palms facing forward.' },
      { sv: 'Ta ett litet steg framåt så att kablarna spänns.', en: 'Step forward slightly to create tension in the cables.' },
      { sv: 'Håll bålen spänd och ryggen rak genom hela övningen.', en: 'Keep your core engaged and your back straight throughout the exercise.' },
      { sv: 'Med lätt böjda armbågar för du långsamt armarna framåt och ihop framför bröstet.', en: 'With a slight bend in your elbows, slowly bring your arms forward and together in front of your chest.' },
      { sv: 'Knip åt i bröstmusklerna i toppen av rörelsen.', en: 'Squeeze your chest muscles at the peak of the movement.' },
      { sv: 'Vänd långsamt rörelsen och för tillbaka armarna till startpositionen.', en: 'Slowly reverse the movement, returning your arms to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelkorsning': {
    equipment: 'Kabel',
    target: 'Bröst',
    secondary: ['Axlar', 'Triceps'],
    steps: [
      { sv: 'Stå mitt i en kabelmaskin med fötterna axelbrett isär.', en: 'Stand in the middle of a cable machine with your feet shoulder-width apart.' },
      { sv: 'Håll kabelhandtagen med handflatorna nedåt och armarna utsträckta rakt ut åt sidorna.', en: 'Hold the handles of the cables with your palms facing down and your arms extended straight out to the sides.' },
      { sv: 'Håll armarna raka och för händerna ihop framför kroppen så att de korsar varandra.', en: 'Keeping your arms straight, bring your hands together in front of your body, crossing them over each other.' },
      { sv: 'Pausa ett ögonblick och återgå sedan långsamt till startpositionen med armarna utsträckta.', en: 'Pause for a moment, then slowly return to the starting position, keeping your arms extended.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelpress': {
    equipment: 'Kabel',
    target: 'Bröst',
    secondary: ['Axlar', 'Triceps'],
    steps: [
      { sv: 'Ställ in sitshöjden och kabelhandtagen i en bekväm position.', en: 'Adjust the seat height and cable handles to a comfortable position.' },
      { sv: 'Sitt på bänken med rak rygg och fötterna i golvet.', en: 'Sit on the bench with your back straight and feet flat on the floor.' },
      { sv: 'Greppa kabelhandtagen med överhandsgrepp i axelhöjd.', en: 'Grasp the cable handles with an overhand grip at shoulder height.' },
      { sv: 'Pressa handtagen framåt och bort från kroppen tills armarna är helt utsträckta.', en: 'Push the handles forward and away from your body, extending your arms fully.' },
      { sv: 'Pausa ett ögonblick och för sedan långsamt tillbaka handtagen till startpositionen.', en: 'Pause for a moment, then slowly bring the handles back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelpullover': {
    equipment: 'Kabel',
    target: 'Lats',
    secondary: ['Triceps', 'Axlar'],
    steps: [
      { sv: 'Fäst ett rep i en kabelmaskin och ställ blocket i det högsta läget.', en: 'Attach a rope to a cable machine and set the pulley at the highest position.' },
      { sv: 'Ligg ner på en bänk med huvudet mot kabelmaskinen.', en: 'Lie down on a bench with your head towards the cable machine.' },
      { sv: 'Håll repet med båda händerna och sträck armarna rakt upp ovanför bröstet.', en: 'Hold the rope with both hands and extend your arms straight up above your chest.' },
      { sv: 'Håll armarna raka och sänk långsamt repet bakom huvudet med bibehållen kontroll.', en: 'Keeping your arms straight, slowly lower the rope behind your head while maintaining control.' },
      { sv: 'Pausa ett ögonblick i botten och lyft sedan långsamt repet tillbaka till startpositionen.', en: 'Pause for a moment at the bottom, then slowly raise the rope back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabelrodd sittande': {
    equipment: 'Kabel',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Sitt i roddmaskinen med fötterna på fotstöden och lätt böjda knän.', en: 'Sit on the cable row machine with your feet flat on the footrests and your knees slightly bent.' },
      { sv: 'Greppa handtagen med överhandsgrepp, håll ryggen rak och axlarna avslappnade.', en: 'Grasp the handles with an overhand grip, keeping your back straight and your shoulders relaxed.' },
      { sv: 'Dra handtagen mot kroppen och pressa ihop skulderbladen.', en: 'Pull the handles towards your body, squeezing your shoulder blades together.' },
      { sv: 'Pausa ett ögonblick i slutet av rörelsen och släpp sedan långsamt tillbaka handtagen till startpositionen.', en: 'Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Kabeltriceps över huvud': {
    equipment: 'Kabel',
    target: 'Triceps',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Fäst ett rep högt upp i en kabelmaskin.', en: 'Attach a rope to a cable machine at a high position.' },
      { sv: 'Stå med ryggen mot maskinen med fötterna axelbrett isär.', en: 'Stand facing away from the machine with your feet shoulder-width apart.' },
      { sv: 'Greppa repet med båda händerna, handflatorna mot varandra, och för händerna ovanför huvudet.', en: 'Grasp the rope with both hands, palms facing each other, and bring your hands above your head.' },
      { sv: 'Håll överarmarna nära huvudet med armbågarna pekande framåt.', en: 'Keep your upper arms close to your head and your elbows pointing forward.' },
      { sv: 'Sänk långsamt repet bakom huvudet genom att böja armbågarna.', en: 'Slowly lower the rope behind your head by bending your elbows.' },
      { sv: 'Pausa ett ögonblick och sträck sedan armarna tillbaka upp till startpositionen.', en: 'Pause for a moment, then extend your arms back up to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
}
