import type { ExerciseInfo } from './types'

// Genererad från det licensierade ExerciseDB-paketet. Svenska steg är
// manuellt översatta, engelska är originalen.
export const PART_4: Record<string, ExerciseInfo> = {
  'Rodd med skivstång': {
    equipment: 'Skivstång',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och knäna lätt böjda.', en: 'Stand with your feet shoulder-width apart and knees slightly bent.' },
      { sv: 'Fäll fram överkroppen från höften med rak rygg och bröstet upp.', en: 'Bend forward at the hips while keeping your back straight and chest up.' },
      { sv: 'Greppa skivstången med överhandsgrepp, händerna något bredare än axelbrett.', en: 'Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.' },
      { sv: 'Dra skivstången mot nedre delen av bröstet genom att dra ihop skulderbladen och spänna ryggmusklerna.', en: 'Pull the barbell towards your lower chest by retracting your shoulder blades and squeezing your back muscles.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt tillbaka skivstången till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the barbell back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Rumänsk marklyft': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Baksida lår', 'Nedre rygg'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och tårna pekande framåt.', en: 'Stand with your feet shoulder-width apart and your toes pointing forward.' },
      { sv: 'Håll skivstången med överhandsgrepp, händerna något bredare än axelbrett.', en: 'Hold the barbell with an overhand grip, hands slightly wider than shoulder-width apart.' },
      { sv: 'Fäll i höften med rak rygg och lätt böjda knän.', en: 'Bend at the hips, keeping your back straight and your knees slightly bent.' },
      { sv: 'Sänk skivstången mot golvet och håll den nära kroppen.', en: 'Lower the barbell towards the ground, keeping it close to your body.' },
      { sv: 'Känn sträckningen i baksida lår när du sänker skivstången.', en: 'Feel the stretch in your hamstrings as you lower the barbell.' },
      { sv: 'När du känner en sträckning i baksida lår, pressa höften framåt och res dig upp igen.', en: 'Once you feel a stretch in your hamstrings, push your hips forward and stand up straight.' },
      { sv: 'Spänn sätesmusklerna i toppen av rörelsen.', en: 'Squeeze your glutes at the top of the movement.' },
      { sv: 'Sänk tillbaka skivstången till startpositionen och upprepa önskat antal repetitioner.', en: 'Lower the barbell back down to the starting position and repeat for the desired number of repetitions.' },
    ],
  },
  'Russian twist': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Sneda magmuskler'],
    steps: [
      { sv: 'Sitt på golvet med böjda knän och fotsulorna i golvet.', en: 'Sit on the ground with your knees bent and feet flat on the floor.' },
      { sv: 'Luta dig bakåt en aning med rak rygg och spänd bål.', en: 'Lean back slightly while keeping your back straight and your core engaged.' },
      { sv: 'Håll ihop händerna framför bröstet, eller håll en vikt om du vill.', en: 'Hold your hands together in front of your chest or hold a weight if desired.' },
      { sv: 'Lyft fötterna från golvet och balansera på sittbenen.', en: 'Lift your feet off the ground, balancing on your sit bones.' },
      { sv: 'Rotera överkroppen åt höger och för händerna eller vikten mot kroppens högra sida.', en: 'Twist your torso to the right, bringing your hands or weight towards the right side of your body.' },
      { sv: 'Pausa ett ögonblick och rotera sedan överkroppen åt vänster, med händerna eller vikten mot kroppens vänstra sida.', en: 'Pause for a moment, then twist your torso to the left, bringing your hands or weight towards the left side of your body.' },
      { sv: 'Fortsätt växla sida önskat antal repetitioner.', en: 'Continue alternating sides for the desired number of repetitions.' },
    ],
  },
  'Shrugs med hantlar': {
    equipment: 'Hantlar',
    target: 'Trapezius',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand med handflatorna vända mot kroppen.', en: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand with your palms facing your body.' },
      { sv: 'Håll armarna raka och låt hantlarna hänga längs sidorna.', en: 'Keep your arms straight and let the dumbbells hang by your sides.' },
      { sv: 'Lyft axlarna så högt som möjligt, som om du försöker nudda öronen med axlarna.', en: 'Raise your shoulders as high as possible, as if you are trying to touch your ears with your shoulders.' },
      { sv: 'Håll kontraktionen en sekund och sänk sedan långsamt axlarna tillbaka till startpositionen.', en: 'Hold the contraction for a second, then slowly lower your shoulders back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Shrugs med skivstång': {
    equipment: 'Skivstång',
    target: 'Trapezius',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en skivstång framför dig med överhandsgrepp.', en: 'Stand with your feet shoulder-width apart and hold a barbell in front of you with an overhand grip.' },
      { sv: 'Håll armarna raka och ryggen rak genom hela övningen.', en: 'Keep your arms straight and your back straight throughout the exercise.' },
      { sv: 'Lyft axlarna upp mot öronen så högt som möjligt och spänn trapezius i toppen.', en: 'Lift your shoulders up towards your ears as high as possible, squeezing your traps at the top.' },
      { sv: 'Håll ett ögonblick och sänk sedan långsamt axlarna tillbaka till startpositionen.', en: 'Hold for a moment, then slowly lower your shoulders back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Sidolyft': {
    equipment: 'Hantlar',
    target: 'Axlar',
    secondary: ['Trapezius'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand med handflatorna mot kroppen.', en: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body.' },
      { sv: 'Håll ryggen rak och spänn bålen.', en: 'Keep your back straight and engage your core.' },
      { sv: 'Lyft armarna ut åt sidorna tills de är parallella med golvet, med en lätt böj i armbågarna.', en: 'Raise your arms out to the sides until they are parallel to the floor, keeping a slight bend in your elbows.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt armarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your arms back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Sidoplanka': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Sneda magmuskler', 'Axlar'],
    steps: [
      { sv: 'Börja med att ligga på sidan med benen utsträckta och staplade på varandra.', en: 'Start by lying on your side with your legs extended and stacked on top of each other.' },
      { sv: 'Placera underarmen i golvet rakt under axeln, med armbågen böjd i 90 grader.', en: 'Place your forearm on the ground directly below your shoulder, with your elbow bent at a 90-degree angle.' },
      { sv: 'Spänn bålen och lyft höften från golvet så att kroppen bildar en rak linje från huvud till fötter.', en: 'Engage your core and lift your hips off the ground, creating a straight line from your head to your feet.' },
      { sv: 'Håll positionen så länge du vill.', en: 'Hold this position for the desired amount of time.' },
      { sv: 'Sänk höften tillbaka till golvet och upprepa på andra sidan.', en: 'Lower your hips back down to the ground and repeat on the other side.' },
    ],
  },
  'Sittande bencurl': {
    equipment: 'Maskin',
    target: 'Baksida lår',
    secondary: ['Vader'],
    steps: [
      { sv: 'Ställ in maskinen efter din kropp och sätt dig med ryggen mot ryggstödet.', en: 'Adjust the machine to fit your body and sit on it with your back against the backrest.' },
      { sv: 'Placera underbenen under den vadderade armen, strax ovanför anklarna.', en: 'Place your lower legs under the padded lever, just above your ankles.' },
      { sv: 'Greppa handtagen på maskinens sidor för stöd.', en: 'Grasp the handles on the sides of the machine for support.' },
      { sv: 'Håll överbenen stilla, andas ut och böj benen så långt som möjligt.', en: 'Keeping your upper legs stationary, exhale and curl your legs up as far as possible.' },
      { sv: 'Håll den kontraherade positionen en kort stund medan du spänner baksida lår.', en: 'Hold the contracted position for a brief pause as you squeeze your hamstrings.' },
      { sv: 'Andas in och sänk långsamt tillbaka armen till startpositionen.', en: 'Inhale and slowly lower the lever back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Sittande vadpress': {
    equipment: 'Skivstång',
    target: 'Vader',
    secondary: ['Baksida lår'],
    steps: [
      { sv: 'Sitt på en bänk med fötterna i golvet och en skivstång vilande på låren.', en: 'Sit on a bench with your feet flat on the floor and a barbell resting on your thighs.' },
      { sv: 'Placera trampdynorna på en upphöjd yta, till exempel en kloss eller ett trappsteg.', en: 'Place the balls of your feet on a raised platform, such as a block or step.' },
      { sv: 'Sänk hälarna så långt som möjligt och känn sträckningen i vaderna.', en: 'Lower your heels as far as possible, feeling a stretch in your calves.' },
      { sv: 'Lyft hälarna så högt som möjligt och spänn vaderna.', en: 'Raise your heels as high as possible, contracting your calves.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Situps': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Höftböjare'],
    steps: [
      { sv: 'Ligg platt på rygg med böjda knän och fotsulorna i golvet.', en: 'Lie flat on your back with your knees bent and feet flat on the ground.' },
      { sv: 'Placera händerna bakom huvudet med armbågarna pekande utåt.', en: 'Place your hands behind your head with your elbows pointing outwards.' },
      { sv: 'Spänn magen och lyft långsamt överkroppen från golvet, rulla framåt tills överkroppen är i 45 graders vinkel.', en: 'Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt tillbaka överkroppen till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your upper body back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Skull crushers': {
    equipment: 'Skivstång',
    target: 'Triceps',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med fötterna i golvet och huvudet vid bänkens kant.', en: 'Lie flat on a bench with your feet flat on the ground and your head at the end of the bench.' },
      { sv: 'Håll skivstången med överhandsgrepp, händerna axelbrett isär, och sträck armarna rakt upp över bröstet.', en: 'Hold the barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest.' },
      { sv: 'Håll överarmarna stilla och sänk långsamt skivstången mot pannan genom att böja armbågarna.', en: 'Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows.' },
      { sv: 'Pausa ett ögonblick när skivstången är strax ovanför pannan och sträck sedan tillbaka armarna till startpositionen.', en: 'Pause for a moment when the barbell is just above your forehead, then extend your arms back up to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Smalbänkpress': {
    equipment: 'Skivstång',
    target: 'Triceps',
    secondary: ['Bröst', 'Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med fötterna i golvet och ryggen pressad mot bänken.', en: 'Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.' },
      { sv: 'Greppa skivstången med smalt grepp, något smalare än axelbrett.', en: 'Grasp the barbell with a close grip, slightly narrower than shoulder-width apart.' },
      { sv: 'Lyft av skivstången från stället och sänk den långsamt mot bröstet med armbågarna nära kroppen.', en: 'Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body.' },
      { sv: 'Pausa ett ögonblick när skivstången nuddar bröstet.', en: 'Pause for a moment when the barbell touches your chest.' },
      { sv: 'Pressa skivstången tillbaka upp till startpositionen med helt sträckta armar.', en: 'Push the barbell back up to the starting position, fully extending your arms.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Steg-ups': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Framsida lår', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Stå framför en bänk eller pall med en skivstång vilande på övre delen av ryggen.', en: 'Stand in front of a bench or step with a barbell resting on your upper back.' },
      { sv: 'Placera ena foten på bänken eller pallen och se till att hela foten har kontakt med ytan.', en: 'Place one foot on the bench or step, ensuring your entire foot is in contact with the surface.' },
      { sv: 'Tryck genom hälen och kliv upp på bänken eller pallen med helt sträckt höft och knä.', en: 'Push through your heel and step up onto the bench or step, fully extending your hip and knee.' },
      { sv: 'Pausa kort i toppen och sänk dig sedan tillbaka till startpositionen.', en: 'Pause briefly at the top, then lower yourself back down to the starting position.' },
      { sv: 'Upprepa med det andra benet.', en: 'Repeat with the opposite leg.' },
      { sv: 'Fortsätt växla ben önskat antal repetitioner.', en: 'Continue alternating legs for the desired number of repetitions.' },
    ],
  },
  'Stående kabelrodd': {
    equipment: 'Kabel',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Axlar'],
    steps: [
      { sv: 'Fäst en rak stång i en kabelmaskin i brösthöjd.', en: 'Attach a straight bar to a cable machine at chest height.' },
      { sv: 'Stå vänd mot maskinen med fötterna axelbrett isär.', en: 'Stand facing the machine with your feet shoulder-width apart.' },
      { sv: 'Greppa stången med överhandsgrepp, händerna något bredare än axelbrett.', en: 'Grasp the bar with an overhand grip, hands slightly wider than shoulder-width apart.' },
      { sv: 'Håll ryggen rak och spänn bålen.', en: 'Keep your back straight and your core engaged.' },
      { sv: 'Dra stången mot övre delen av bröstet och pressa ihop skulderbladen.', en: 'Pull the bar towards your upper chest, squeezing your shoulder blades together.' },
      { sv: 'Pausa ett ögonblick i toppen av rörelsen.', en: 'Pause for a moment at the top of the movement.' },
      { sv: 'Släpp långsamt tillbaka stången till startpositionen.', en: 'Slowly release the bar back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Sumo marklyft': {
    equipment: 'Skivstång',
    target: 'Säte',
    secondary: ['Baksida lår', 'Framsida lår', 'Nedre rygg'],
    steps: [
      { sv: 'Stå med fötterna bredare än axelbrett och tårna pekande utåt.', en: 'Stand with your feet wider than shoulder-width apart, toes pointing outwards.' },
      { sv: 'Placera en skivstång på golvet framför dig, centrerad mellan fötterna.', en: 'Place a barbell on the ground in front of you, centered between your feet.' },
      { sv: 'Böj knäna och sänk höften, med rak rygg och bröstet upp, och greppa skivstången med överhandsgrepp.', en: 'Bend your knees and lower your hips, keeping your back straight and chest up, to grip the barbell with an overhand grip.' },
      { sv: 'Spänn bålen och tryck genom hälarna för att lyfta skivstången från golvet, sträck höft och knän samtidigt.', en: 'Engage your core and drive through your heels to lift the barbell off the ground, extending your hips and knees simultaneously.' },
      { sv: 'Håll bröstet upp och ryggen rak under lyftet, och pressa höften framåt för att aktivera sätet fullt ut.', en: 'As you lift, keep your chest up and back straight, and push your hips forward to fully engage your glutes.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt tillbaka skivstången till startpositionen med kontroll genom hela rörelsen.', en: 'Pause for a moment at the top, then slowly lower the barbell back down to the starting position, maintaining control throughout the movement.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'T-bar rodd': {
    equipment: 'Maskin',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Ställ in sitshöjden och fotplattans läge så att du sitter rätt.', en: 'Adjust the seat height and footplate position to ensure proper alignment.' },
      { sv: 'Sitt i maskinen med bröstet mot dynan och fötterna platt på fotplattan.', en: 'Sit on the machine with your chest against the pad and your feet flat on the footplate.' },
      { sv: 'Greppa handtagen med överhandsgrepp, något bredare än axelbrett.', en: 'Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.' },
      { sv: 'Håll ryggen rak och spänn bålen.', en: 'Keep your back straight and engage your core.' },
      { sv: 'Dra handtagen mot överkroppen och pressa ihop skulderbladen.', en: 'Pull the handles towards your torso, squeezing your shoulder blades together.' },
      { sv: 'Pausa ett ögonblick i den maximala kontraktionen och släpp sedan långsamt tillbaka handtagen till startpositionen.', en: 'Pause for a moment at the peak contraction, then slowly release the handles back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Thrusters': {
    equipment: 'Skivstång',
    target: 'Axlar',
    secondary: ['Framsida lår', 'Säte', 'Baksida lår', 'Bål'],
    steps: [
      { sv: 'Börja stående med fötterna axelbrett isär och håll en skivstång i axelhöjd med överhandsgrepp.', en: 'Start by standing with your feet shoulder-width apart, holding a barbell at shoulder height with an overhand grip.' },
      { sv: 'Sänk dig ner i en knäböj genom att böja knäna och skjuta höften bakåt.', en: 'Lower into a squat position by bending your knees and pushing your hips back.' },
      { sv: 'När du når botten av knäböjen, tryck explosivt genom hälarna för att resa dig upp och pressa samtidigt skivstången över huvudet.', en: 'As you reach the bottom of the squat, explosively drive through your heels to stand up, simultaneously pressing the barbell overhead.' },
      { sv: 'Sänk skivstången tillbaka till axelhöjd samtidigt som du sänker dig ner i knäböjen igen.', en: 'Lower the barbell back to shoulder height as you lower back into the squat position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Triceps kickback': {
    equipment: 'Hantlar',
    target: 'Triceps',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand.', en: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand.' },
      { sv: 'Böj knäna en aning och fäll fram från höften med rak rygg.', en: 'Bend your knees slightly and hinge forward at the hips, keeping your back straight.' },
      { sv: 'Håll överarmarna nära kroppens sidor med armbågarna böjda i 90 grader.', en: 'Bring your upper arms close to your sides, with your elbows bent at a 90-degree angle.' },
      { sv: 'Sträck armarna rakt bakåt och spänn triceps i toppen av rörelsen.', en: 'Extend your arms straight back, squeezing your triceps at the top of the movement.' },
      { sv: 'Pausa ett ögonblick och sänk sedan långsamt tillbaka hantlarna till startpositionen.', en: 'Pause for a moment, then slowly lower the dumbbells back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Tricepspress smal': {
    equipment: 'Skivstång',
    target: 'Triceps',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med fötterna i golvet och huvudet vid bänkens kant.', en: 'Lie flat on a bench with your feet flat on the ground and your head at the end of the bench.' },
      { sv: 'Greppa skivstången med smalt grepp, händerna axelbrett isär och handflatorna uppåt.', en: 'Grasp the barbell with a close grip, hands shoulder-width apart, palms facing up.' },
      { sv: 'Sträck armarna helt och lyft skivstången ovanför bröstet.', en: 'Extend your arms fully, lifting the barbell above your chest.' },
      { sv: 'Håll överarmarna stilla och sänk långsamt skivstången mot pannan genom att böja armbågarna.', en: 'Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows.' },
      { sv: 'Pausa ett ögonblick i botten och sträck sedan tillbaka armarna till startpositionen.', en: 'Pause for a moment at the bottom, then extend your arms back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Tricepsstötning kabel': {
    equipment: 'Kabel',
    target: 'Triceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Fäst en rak stång i det övre blocket på en kabelmaskin.', en: 'Attach a straight bar to a high pulley cable machine.' },
      { sv: 'Stå vänd mot maskinen med fötterna axelbrett isär och en lätt böj i knäna.', en: 'Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees.' },
      { sv: 'Greppa stången med överhandsgrepp, händerna axelbrett isär.', en: 'Grasp the bar with an overhand grip, hands shoulder-width apart.' },
      { sv: 'Håll armbågarna nära sidorna och överarmarna stilla.', en: 'Keep your elbows close to your sides and your upper arms stationary.' },
      { sv: 'Andas ut och pressa ner stången tills armbågarna är helt sträckta.', en: 'Exhale and push the bar down until your elbows are fully extended.' },
      { sv: 'Pausa ett ögonblick, andas sedan in och för långsamt tillbaka stången till startpositionen.', en: 'Pause for a moment, then inhale and slowly return the bar to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Tricepsstötning med rep': {
    equipment: 'Kabel',
    target: 'Triceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Fäst ett rep i det övre blocket på en kabelmaskin.', en: 'Attach a rope attachment to a high pulley on a cable machine.' },
      { sv: 'Stå vänd mot maskinen med fötterna axelbrett isär och en lätt böj i knäna.', en: 'Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees.' },
      { sv: 'Greppa repet med överhandsgrepp och handflatorna vända mot varandra.', en: 'Grasp the rope with an overhand grip, palms facing each other.' },
      { sv: 'Håll armbågarna nära sidorna och överarmarna stilla genom hela övningen.', en: 'Keep your elbows close to your sides and your upper arms stationary throughout the exercise.' },
      { sv: 'Andas ut och pressa repet nedåt genom att sträcka armbågarna tills armarna är helt raka.', en: 'Exhale and push the rope downward by extending your elbows until your arms are fully extended.' },
      { sv: 'Pausa ett ögonblick, andas sedan in och återgå långsamt till startpositionen genom att låta armbågarna böjas.', en: 'Pause for a moment, then inhale and slowly return to the starting position by allowing your elbows to flex.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Upright row': {
    equipment: 'Skivstång',
    target: 'Axlar',
    secondary: ['Trapezius', 'Biceps'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en skivstång med överhandsgrepp, händerna något bredare än axelbrett.', en: 'Stand with your feet shoulder-width apart and hold a barbell with an overhand grip, hands slightly wider than shoulder-width apart.' },
      { sv: 'Låt skivstången hänga framför låren med helt sträckta armar.', en: 'Let the barbell hang in front of your thighs, arms fully extended.' },
      { sv: 'Håll ryggen rak och bålen spänd, andas ut och lyft skivstången rakt upp mot hakan med armbågarna först.', en: 'Keeping your back straight and core engaged, exhale and lift the barbell straight up towards your chin, leading with your elbows.' },
      { sv: 'Pausa ett ögonblick i toppen, andas sedan in och sänk långsamt tillbaka skivstången till startpositionen.', en: 'Pause for a moment at the top, then inhale and slowly lower the barbell back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Utfall': {
    equipment: 'Hantlar',
    target: 'Säte',
    secondary: ['Framsida lår', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand.', en: 'Stand with your feet shoulder-width apart, holding a dumbbell in each hand.' },
      { sv: 'Ta ett steg framåt med höger fot och sänk kroppen ner i ett utfall.', en: 'Take a step forward with your right foot, lowering your body into a lunge position.' },
      { sv: 'Håll ryggen rak och bröstet upp när du sänker kroppen.', en: 'Keep your back straight and your chest up as you lower your body.' },
      { sv: 'Tryck genom höger häl för att återgå till startpositionen.', en: 'Push through your right heel to return to the starting position.' },
      { sv: 'Upprepa med vänster ben.', en: 'Repeat with your left leg.' },
      { sv: 'Växla ben önskat antal repetitioner.', en: 'Alternate legs for the desired number of repetitions.' },
    ],
  },
  'Vadpress stående': {
    equipment: 'Skivstång',
    target: 'Vader',
    secondary: ['Baksida lår', 'Säte'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och placera en skivstång över övre delen av ryggen.', en: 'Stand with your feet shoulder-width apart and place a barbell across your upper back.' },
      { sv: 'Lyft hälarna från golvet så högt som möjligt och stå bara på tårna.', en: 'Raise your heels off the ground as high as possible, using only your toes.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt tillbaka hälarna till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your heels back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
}
