import type { ExerciseInfo } from './types'

// Genererad från det licensierade ExerciseDB-paketet. Svenska steg är
// manuellt översatta, engelska är originalen.
export const PART_1: Record<string, ExerciseInfo> = {
  'Ab wheel': {
    equipment: 'Träningshjul',
    target: 'Magmuskler',
    secondary: ['Nedre rygg'],
    steps: [
      { sv: 'Stå på knä på golvet och placera träningshjulet framför dig.', en: 'Kneel on the floor and place the wheel roller in front of you.' },
      { sv: 'Greppa hjulets handtag och sträck armarna rakt fram framför dig.', en: 'Place your hands on the handles of the wheel roller and extend your arms straight out in front of you.' },
      { sv: 'Spänn bålen och rulla hjulet långsamt framåt med rak rygg och spänd mage.', en: 'Engage your core muscles and slowly roll the wheel forward, keeping your back straight and your abs tight.' },
      { sv: 'Fortsätt rulla framåt tills kroppen är helt utsträckt och armarna är ovanför huvudet.', en: 'Continue rolling forward until your body is fully extended and your arms are overhead.' },
      { sv: 'Pausa ett ögonblick och rulla sedan långsamt tillbaka hjulet mot knäna med kontroll och spänd mage.', en: 'Pause for a moment, then slowly roll the wheel back towards your knees, maintaining control and keeping your abs engaged.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Arnold press': {
    equipment: 'Hantlar',
    target: 'Axlar',
    secondary: ['Triceps', 'Övre bröst'],
    steps: [
      { sv: 'Sitt på en bänk med ryggstöd och håll en hantel i varje hand i axelhöjd, med handflatorna mot kroppen och böjda armbågar.', en: 'Sit on a bench with back support and hold a dumbbell in each hand at shoulder level, palms facing your body and elbows bent.' },
      { sv: 'Pressa hantlarna uppåt tills armarna är helt sträckta och handflatorna pekar framåt.', en: 'Press the dumbbells upward until your arms are fully extended and your palms are facing forward.' },
      { sv: 'Rotera handlederna under pressen så att handflatorna pekar framåt i rörelsens topp.', en: 'Rotate your wrists as you lift, so that your palms are facing forward at the top of the movement.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt hantlarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the dumbbells back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Axellyft med kabel': {
    equipment: 'Kabel',
    target: 'Axlar',
    secondary: ['Trapezius', 'Triceps'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och greppa kabelhandtagen med överhandsgrepp.', en: 'Stand with your feet shoulder-width apart and grasp the cable handles with an overhand grip.' },
      { sv: 'Håll armarna raka och bålen spänd.', en: 'Keep your arms straight and your core engaged.' },
      { sv: 'Lyft armarna ut åt sidorna tills de är parallella med golvet.', en: 'Raise your arms out to the sides until they are parallel to the floor.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt armarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your arms back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Bakre deltalyft': {
    equipment: 'Hantlar',
    target: 'Axlar',
    secondary: ['Trapezius', 'Romboider'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i varje hand med handflatorna mot kroppen.', en: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body.' },
      { sv: 'Böj knäna lätt och fäll fram i höften med rak rygg och spänd bål.', en: 'Bend your knees slightly and hinge forward at the hips, keeping your back straight and core engaged.' },
      { sv: 'Lyft armarna ut åt sidorna med en lätt böj i armbågarna tills de är parallella med golvet.', en: 'Raise your arms out to the sides, keeping a slight bend in your elbows, until they are parallel to the floor.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt armarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your arms back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Bakre deltalyft i kabel': {
    equipment: 'Kabel',
    target: 'Axlar',
    secondary: ['Trapezius', 'Romboider'],
    steps: [
      { sv: 'Sitt på en bänk vänd mot kabelmaskinen med fötterna platt i golvet.', en: 'Sit on a bench facing the cable machine with your feet flat on the ground.' },
      { sv: 'Greppa kabelhandtagen med överhandsgrepp och sträck armarna rakt fram.', en: 'Grasp the cable handles with an overhand grip and extend your arms straight in front of you.' },
      { sv: 'Håll armarna raka och lyft dem långsamt ut åt sidorna tills de är parallella med golvet.', en: 'Keeping your arms straight, slowly raise them out to the sides until they are parallel to the floor.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt armarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your arms back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Bencurl liggande': {
    equipment: 'Maskin',
    target: 'Baksida lår',
    secondary: ['Vader'],
    steps: [
      { sv: 'Ställ in maskinen efter din kropp och välj önskad vikt.', en: 'Adjust the machine to fit your body and select the desired weight.' },
      { sv: 'Ligg på mage i maskinen med raka ben och hälarna mot den vadderade hävarmen.', en: 'Lie face down on the machine with your legs straight and your heels against the padded lever.' },
      { sv: 'Greppa handtagen eller maskinens sidor för stabilitet.', en: 'Grasp the handles or the sides of the machine for stability.' },
      { sv: 'Håll överkroppen stilla, andas ut och böj benen så långt det går utan att lyfta höfterna från dynan.', en: 'Keeping your upper body stationary, exhale and curl your legs up as far as possible without lifting your hips off the pad.' },
      { sv: 'Håll den sammandragna positionen en kort stund medan du kniper ihop baksida lår.', en: 'Hold the contracted position for a brief pause as you squeeze your hamstrings.' },
      { sv: 'Andas in och sänk långsamt hävarmen tillbaka till startpositionen.', en: 'Inhale and slowly lower the lever back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Benextension': {
    equipment: 'Maskin',
    target: 'Framsida lår',
    secondary: ['Baksida lår'],
    steps: [
      { sv: 'Ställ in maskinens sitthöjd och ryggstöd efter din kropp.', en: 'Adjust the seat height and backrest of the machine to fit your body.' },
      { sv: 'Sitt i maskinen med ryggen mot ryggstödet och fötterna mot fotdynan.', en: 'Sit on the machine with your back against the backrest and your feet on the footpad.' },
      { sv: 'Greppa handtagen eller sidostängerna för stabilitet.', en: 'Grasp the handles or sidebars for stability.' },
      { sv: 'Sträck benen framåt genom att räta ut knäna och lyfta vikten.', en: 'Extend your legs forward by straightening your knees, lifting the weight.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt vikten tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the weight back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Benlyft liggande': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Höftböjare'],
    steps: [
      { sv: 'Ligg platt på en plan bänk med ryggen pressad mot den.', en: 'Lie flat on a flat bench with your back pressed against it.' },
      { sv: 'Placera händerna under rumpan som stöd.', en: 'Place your hands under your glutes for support.' },
      { sv: 'Håll benen raka och ihop och lyft dem upp mot taket.', en: 'Keep your legs straight and together, and lift them up towards the ceiling.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt benen tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your legs back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Benpress': {
    equipment: 'Maskin',
    target: 'Säte',
    secondary: ['Framsida lår', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Ställ in sitsen och fotplattan i maskinen till en bekväm position.', en: 'Adjust the seat and footplate of the sled machine to a comfortable position.' },
      { sv: 'Sitt i maskinen med ryggen mot ryggstödet och fötterna axelbrett isär på fotplattan.', en: 'Sit on the sled machine with your back against the backrest and your feet shoulder-width apart on the footplate.' },
      { sv: 'Greppa handtagen vid sitsens sidor för stabilitet.', en: 'Grip the handles on the sides of the seat for stability.' },
      { sv: 'Pressa fotplattan bort från kroppen genom att sträcka benen, med hälarna kvar på plattan.', en: 'Push the footplate away from your body by extending your legs, keeping your heels on the footplate.' },
      { sv: 'Fortsätt pressa tills benen är nästan helt sträckta, men utan att låsa knäna.', en: 'Continue pushing until your legs are almost fully extended, but without locking your knees.' },
      { sv: 'Pausa ett ögonblick i rörelsens topp och sänk sedan långsamt fotplattan tillbaka mot kroppen genom att böja knäna.', en: 'Pause for a moment at the top of the movement, then slowly lower the footplate back towards your body by bending your knees.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Bicepscurl': {
    equipment: 'Hantlar',
    target: 'Biceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Stå upprätt med en hantel i varje hand, handflatorna framåt och armarna helt sträckta.', en: 'Stand up straight with a dumbbell in each hand, palms facing forward and arms fully extended.' },
      { sv: 'Håll överarmarna stilla, andas ut och curla vikterna medan du spänner biceps.', en: 'Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.' },
      { sv: 'Fortsätt lyfta vikterna tills biceps är helt sammandragna och hantlarna är i axelhöjd.', en: 'Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.' },
      { sv: 'Håll den sammandragna positionen en kort stund medan du kniper ihop biceps.', en: 'Hold the contracted position for a brief pause as you squeeze your biceps.' },
      { sv: 'Andas in och börja långsamt sänka hantlarna tillbaka till startpositionen.', en: 'Inhale and slowly begin to lower the dumbbells back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Box squat': {
    equipment: 'Skivstång',
    target: 'Framsida lår',
    secondary: ['Säte', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Placera en skivstång i ett knäböjsställ i brösthöjd.', en: 'Set up a barbell on a squat rack at chest height.' },
      { sv: 'Stå med ryggen mot stället och fötterna axelbrett isär.', en: 'Stand facing away from the rack, with your feet shoulder-width apart.' },
      { sv: 'Böj knäna och sänk kroppen ner i knäböjsposition med rak rygg och bröstet uppåt.', en: 'Bend your knees and lower your body down into a squat position, keeping your back straight and chest up.' },
      { sv: 'Greppa skivstången med överhandsgrepp, något bredare än axelbrett.', en: 'Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.' },
      { sv: 'Lyft av skivstången från stället och kliv bakåt, med fötterna fortfarande axelbrett isär.', en: 'Lift the barbell off the rack and step back, ensuring your feet are still shoulder-width apart.' },
      { sv: 'Sänk kroppen ner i en knäböj med knäna i linje med tårna.', en: 'Lower your body down into a squat, keeping your knees in line with your toes.' },
      { sv: 'Pausa ett ögonblick i botten och pressa sedan genom hälarna tillbaka till startpositionen.', en: 'Pause for a moment at the bottom, then push through your heels to return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Bulgariska utfall': {
    equipment: 'Ingen utrustning',
    target: 'Framsida lår',
    secondary: ['Säte', 'Baksida lår', 'Vader'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär.', en: 'Stand with your feet shoulder-width apart.' },
      { sv: 'Ta ett steg framåt med ena foten och placera den ungefär en halvmeter framför den andra.', en: 'Take a step forward with one foot and place it about two feet in front of the other foot.' },
      { sv: 'Sänk kroppen genom att böja knän och höfter med rak rygg.', en: 'Lower your body by bending your knees and hips, keeping your back straight.' },
      { sv: 'Fortsätt sänka tills främre låret är parallellt med golvet och bakre knät svävar strax ovanför golvet.', en: 'Continue lowering until your front thigh is parallel to the ground, and your back knee is hovering just above the ground.' },
      { sv: 'Pausa ett ögonblick och pressa sedan genom främre hälen tillbaka till startpositionen.', en: 'Pause for a moment, then push through your front heel to return to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner och byt sedan ben och upprepa.', en: 'Repeat for the desired number of repetitions, then switch legs and repeat.' },
    ],
  },
  'Bänkpress': {
    equipment: 'Skivstång',
    target: 'Bröst',
    secondary: ['Triceps', 'Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med fötterna i golvet och ryggen pressad mot bänken.', en: 'Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.' },
      { sv: 'Greppa skivstången med överhandsgrepp, något bredare än axelbrett.', en: 'Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.' },
      { sv: 'Lyft av skivstången från stället och håll den rakt ovanför bröstet med helt sträckta armar.', en: 'Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.' },
      { sv: 'Sänk skivstången långsamt mot bröstet med armbågarna intill kroppen.', en: 'Lower the barbell slowly towards your chest, keeping your elbows tucked in.' },
      { sv: 'Pausa ett ögonblick när skivstången nuddar bröstet.', en: 'Pause for a moment when the barbell touches your chest.' },
      { sv: 'Pressa skivstången tillbaka upp till startpositionen genom att sträcka armarna.', en: 'Push the barbell back up to the starting position by extending your arms.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Chin-ups': {
    equipment: 'Ingen utrustning',
    target: 'Lats',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Häng i en chinsstång med handflatorna mot dig och händerna axelbrett isär.', en: 'Hang from a pull-up bar with your palms facing towards you and your hands shoulder-width apart.' },
      { sv: 'Spänn bålen och dra kroppen upp mot stången med bröstet först.', en: 'Engage your core and pull your body up towards the bar, leading with your chest.' },
      { sv: 'Fortsätt dra tills hakan är ovanför stången.', en: 'Continue pulling until your chin is above the bar.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt kroppen tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your body back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Crunches': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Höftböjare'],
    steps: [
      { sv: 'Ligg platt på rygg med böjda knän och fötterna i golvet.', en: 'Lie flat on your back with your knees bent and feet flat on the ground.' },
      { sv: 'Placera händerna bakom huvudet med armbågarna pekande utåt.', en: 'Place your hands behind your head with your elbows pointing outwards.' },
      { sv: 'Spänn magen och lyft axlarna från golvet genom att rulla framåt mot knäna.', en: 'Engage your abs and lift your shoulders off the ground, curling forward towards your knees.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt axlarna tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your shoulders back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Decline bänkpress': {
    equipment: 'Skivstång',
    target: 'Bröst',
    secondary: ['Triceps', 'Axlar'],
    steps: [
      { sv: 'Ligg på en nedåtlutande bänk med fötterna fastspända och huvudet lägre än höfterna.', en: 'Lie on a decline bench with your feet secured and your head lower than your hips.' },
      { sv: 'Greppa skivstången med överhandsgrepp, något bredare än axelbrett.', en: 'Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.' },
      { sv: 'Lyft av skivstången från stället och sänk den långsamt mot bröstet med armbågarna intill kroppen.', en: 'Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.' },
      { sv: 'Pausa ett ögonblick i botten och pressa sedan skivstången tillbaka upp till startpositionen.', en: 'Pause for a moment at the bottom, then push the barbell back up to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Dips': {
    equipment: 'Ingen utrustning',
    target: 'Bröst',
    secondary: ['Triceps', 'Axlar'],
    steps: [
      { sv: 'Placera dig mellan parallella räcken med helt sträckta armar och rak kropp.', en: 'Position yourself on parallel bars with your arms fully extended and your body straight.' },
      { sv: 'Sänk kroppen genom att böja armbågarna tills axlarna är nedanför armbågarna.', en: 'Lower your body by bending your elbows until your shoulders are below your elbows.' },
      { sv: 'Pressa dig tillbaka upp till startpositionen genom att sträcka armarna.', en: 'Push yourself back up to the starting position by straightening your arms.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Dragon flag': {
    equipment: 'Ingen utrustning',
    target: 'Magmuskler',
    secondary: ['Sneda magmuskler', 'Axlar'],
    steps: [
      { sv: 'Börja med att greppa en vertikal stång med båda händerna, handflatorna mot varandra och helt sträckta armar.', en: 'Start by gripping a vertical pole with both hands, palms facing each other, and arms fully extended.' },
      { sv: 'Spänn bålen och lyft benen från golvet med benen raka.', en: 'Engage your core and lift your legs off the ground, keeping them straight.' },
      { sv: 'Använd bålen och överkroppens styrka för att lyfta benen tills de är parallella med golvet.', en: 'Using your core and upper body strength, raise your legs until they are parallel to the ground.' },
      { sv: 'Håll positionen så länge du kan med en rak kroppslinje.', en: 'Hold this position for as long as you can, maintaining a straight body line.' },
      { sv: 'Sänk långsamt benen tillbaka till startpositionen.', en: 'Slowly lower your legs back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Enarms hantelrodd': {
    equipment: 'Hantlar',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Stå med fötterna axelbrett isär och håll en hantel i ena handen med handflatan mot kroppen.', en: 'Stand with your feet shoulder-width apart, holding a dumbbell in one hand with your palm facing your body.' },
      { sv: 'Böj knäna lätt och fäll fram i höften med rak rygg och spänd bål.', en: 'Bend your knees slightly and hinge forward at the hips, keeping your back straight and your core engaged.' },
      { sv: 'Låt hanteln hänga rakt ner mot golvet med armen helt sträckt.', en: 'Let the dumbbell hang straight down towards the floor, with your arm fully extended.' },
      { sv: 'Dra hanteln upp mot bröstet med armbågen nära kroppen och kläm ihop skulderbladen.', en: 'Pull the dumbbell up towards your chest, keeping your elbow close to your body and squeezing your shoulder blades together.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt hanteln tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower the dumbbell back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner och byt sedan sida.', en: 'Repeat for the desired number of repetitions, then switch sides.' },
    ],
  },
  'Enarms kabelcurl': {
    equipment: 'Kabel',
    target: 'Biceps',
    secondary: ['Underarmar'],
    steps: [
      { sv: 'Stå vänd mot kabelmaskinen med fötterna axelbrett isär.', en: 'Stand facing the cable machine with your feet shoulder-width apart.' },
      { sv: 'Greppa kabelhandtaget med underhandsgrepp, handflatan uppåt.', en: 'Grasp the cable handle with an underhand grip, palm facing up.' },
      { sv: 'Håll armbågen nära sidan och curla långsamt underarmen upp mot axeln.', en: 'Keep your elbow close to your side and slowly curl your forearm up towards your shoulder.' },
      { sv: 'Pausa ett ögonblick i toppen och sänk sedan långsamt underarmen tillbaka till startpositionen.', en: 'Pause for a moment at the top, then slowly lower your forearm back down to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Enarms kabelrodd': {
    equipment: 'Kabel',
    target: 'Övre rygg',
    secondary: ['Biceps', 'Underarmar'],
    steps: [
      { sv: 'Stå vänd mot kabelmaskinen med fötterna axelbrett isär.', en: 'Stand facing a cable machine with your feet shoulder-width apart.' },
      { sv: 'Böj knäna lätt och fäll fram i höften med rak rygg.', en: 'Bend your knees slightly and hinge forward at the hips, keeping your back straight.' },
      { sv: 'Greppa kabelhandtaget med ena handen, handflatan inåt, och sträck ut armen helt.', en: 'Grasp the cable handle with one hand, palm facing inward, and extend your arm fully.' },
      { sv: 'Dra handtaget mot kroppen med armbågen nära sidan tills handen når nedre delen av bröstet.', en: 'Pull the cable handle towards your body, keeping your elbow close to your side, until your hand reaches your lower chest.' },
      { sv: 'Pausa ett ögonblick och sträck sedan långsamt tillbaka armen till startpositionen.', en: 'Pause for a moment, then slowly extend your arm back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner och byt sedan sida.', en: 'Repeat for the desired number of repetitions, then switch sides.' },
    ],
  },
  'Face pulls': {
    equipment: 'Kabel',
    target: 'Axlar',
    secondary: ['Trapezius', 'Romboider', 'Biceps'],
    steps: [
      { sv: 'Stå vänd mot kabelmaskinen med fötterna axelbrett isär.', en: 'Stand facing a cable machine with your feet shoulder-width apart.' },
      { sv: 'Håll kabelfästet med båda händerna, handflatorna mot varandra, och kliv bakåt så att kabeln spänns.', en: 'Hold the cable attachment with both hands, palms facing each other, and step back to create tension in the cable.' },
      { sv: 'Håll ryggen rak och bålen spänd.', en: 'Keep your back straight and your core engaged.' },
      { sv: 'Dra kabeln mot kroppen och kläm ihop skulderbladen.', en: 'Pull the cable towards your body, squeezing your shoulder blades together.' },
      { sv: 'Pausa ett ögonblick i rörelsens topp och släpp sedan långsamt tillbaka kabeln till startpositionen.', en: 'Pause for a moment at the peak of the movement, then slowly release the cable back to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Farmers walk': {
    equipment: 'Hantlar',
    target: 'Framsida lår',
    secondary: ['Vader', 'Underarmar', 'Bål'],
    steps: [
      { sv: 'Stå upprätt med en hantel i varje hand, handflatorna mot sidorna.', en: 'Stand up straight with a dumbbell in each hand, palms facing your sides.' },
      { sv: 'Håll ryggen rak och axlarna bakåt.', en: 'Keep your back straight and your shoulders back.' },
      { sv: 'Ta små, kontrollerade steg framåt med bibehållen upprätt hållning.', en: 'Take small, controlled steps forward, maintaining an upright posture.' },
      { sv: 'Fortsätt gå önskad sträcka eller tid.', en: 'Continue walking for the desired distance or time.' },
      { sv: 'Avsluta genom att stanna och försiktigt sänka hantlarna till sidorna.', en: 'To finish, stop walking and carefully lower the dumbbells to your sides.' },
    ],
  },
  'Flyes med hantlar': {
    equipment: 'Hantlar',
    target: 'Bröst',
    secondary: ['Axlar'],
    steps: [
      { sv: 'Ligg platt på en bänk med en hantel i varje hand, handflatorna mot varandra.', en: 'Lie flat on a bench with a dumbbell in each hand, palms facing each other.' },
      { sv: 'Sträck armarna rakt upp över bröstet med en lätt böj i armbågarna.', en: 'Extend your arms straight up over your chest, with a slight bend in your elbows.' },
      { sv: 'Behåll den lätta böjen i armbågarna och sänk armarna ut åt sidorna i en vid båge tills du känner att det sträcker i bröstet.', en: 'Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.' },
      { sv: 'Pausa ett ögonblick, vänd sedan rörelsen och för hantlarna tillbaka upp till startpositionen.', en: 'Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
  'Frivändning': {
    equipment: 'Skivstång',
    target: 'Baksida lår',
    secondary: ['Säte', 'Framsida lår', 'Vader'],
    steps: [
      { sv: 'Börja med skivstången på golvet framför dig, med fötterna axelbrett isär.', en: 'Start with the barbell on the ground in front of you, with your feet shoulder-width apart.' },
      { sv: 'Böj dig ner och greppa skivstången med överhandsgrepp, något bredare än axelbrett.', en: 'Bend down and grip the barbell with an overhand grip, slightly wider than shoulder-width apart.' },
      { sv: 'Håll ryggen rak och bröstet uppåt medan du lyfter skivstången från golvet genom att sträcka höfter och knän.', en: 'Keep your back straight and chest up as you lift the barbell off the ground, extending your hips and knees.' },
      { sv: 'När skivstången når mitten av låren drar du den explosivt uppåt, rycker upp axlarna och drar armbågarna högt ut åt sidorna.', en: 'As the barbell reaches your mid-thigh, explosively pull it upwards, shrugging your shoulders and pulling your elbows high and to the sides.' },
      { sv: 'När skivstången når sin högsta punkt dyker du snabbt under den, roterar armbågarna runt och fångar stången på axlarna i en frontböjsposition.', en: 'As the barbell reaches its highest point, quickly drop underneath it, rotating your elbows around and catching the barbell on your shoulders in a front squat position.' },
      { sv: 'Res dig upp med skivstången och sträck ut höfter och knän helt.', en: 'Stand up with the barbell, fully extending your hips and knees.' },
      { sv: 'Sänk skivstången tillbaka till startpositionen med kontroll över vikten genom hela rörelsen.', en: 'Lower the barbell back down to the starting position, keeping control of the weight throughout the movement.' },
      { sv: 'Upprepa önskat antal repetitioner.', en: 'Repeat for the desired number of repetitions.' },
    ],
  },
}
