-- Tecknade illustrationer från Everkinetic (CC BY-SA 4.0) ersätter fotona.
-- Omatchade övningar får ikon-fallback (image_path NULL). Idempotent.

UPDATE exercises SET image_path = NULL WHERE image_path LIKE '%.jpg';
UPDATE exercises SET image_path = 'ab-rollout-on-knees-with-barbell.png' WHERE name = 'Ab wheel' AND category = 'strength';
UPDATE exercises SET image_path = 'one-arm-dumbbell-shoulder-press.png' WHERE name = 'Arnold press' AND category = 'strength';
UPDATE exercises SET image_path = 'bent-over-rear-deltoid-raise-with-head-on-bench.png' WHERE name = 'Bakre deltalyft' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-rear-lateral-cable-raise.png' WHERE name = 'Bakre deltalyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'lying-leg-curl-machine.png' WHERE name = 'Bencurl liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'leg-extensions.png' WHERE name = 'Benextension' AND category = 'strength';
UPDATE exercises SET image_path = 'flat-bench-leg-raises.png' WHERE name = 'Benlyft liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'leg-press.png' WHERE name = 'Benpress' AND category = 'strength';
UPDATE exercises SET image_path = 'biceps-curl-with-dumbbell.png' WHERE name = 'Bicepscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'squat-to-bench-with-barbell.png' WHERE name = 'Box squat' AND category = 'strength';
UPDATE exercises SET image_path = 'bench-press.png' WHERE name = 'Bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'wide-grip-chin-up.png' WHERE name = 'Chin-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'crunches.png' WHERE name = 'Crunches' AND category = 'strength';
UPDATE exercises SET image_path = 'decline-barbell-bench-press.png' WHERE name = 'Decline bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'chest-dips.png' WHERE name = 'Dips' AND category = 'strength';
UPDATE exercises SET image_path = 'standing-one-arm-biceps-curl-with-cable.png' WHERE name = 'Enarms kabelcurl' AND category = 'strength';
UPDATE exercises SET image_path = 'dumbbell-flys.png' WHERE name = 'Flyes med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'front-squat-with-barbell.png' WHERE name = 'Front squat' AND category = 'strength';
UPDATE exercises SET image_path = 'front-dumbbell-raise.png' WHERE name = 'Frontlyft' AND category = 'strength';
UPDATE exercises SET image_path = 'front-cable-raises.png' WHERE name = 'Frontlyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'one-legged-cable-kickback.png' WHERE name = 'Glute kickback i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'barbell-good-mornings.png' WHERE name = 'Good mornings' AND category = 'strength';
UPDATE exercises SET image_path = 'hack-squat-machine.png' WHERE name = 'Hack squat' AND category = 'strength';
UPDATE exercises SET image_path = 'biceps-hammer-curl-with-dumbbell.png' WHERE name = 'Hammercurl' AND category = 'strength';
UPDATE exercises SET image_path = 'one-arm-dumbbell-shoulder-press.png' WHERE name = 'Hantelpress axlar' AND category = 'strength';
UPDATE exercises SET image_path = 'bench-press-dumbbell.png' WHERE name = 'Hantelpress liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'bridging.png' WHERE name = 'Hip thrust' AND category = 'strength';
UPDATE exercises SET image_path = 'hyperextensions.png' WHERE name = 'Hyperextensions' AND category = 'strength';
UPDATE exercises SET image_path = 'thigh-abductor.png' WHERE name = 'Höftabduktion i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'standing-biceps-curl-with-cable.png' WHERE name = 'Kabelbiceps' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-ab-crunch-with-cable.png' WHERE name = 'Kabelcrunch' AND category = 'strength';
UPDATE exercises SET image_path = 'hammer-curls-with-rope-and-cable.png' WHERE name = 'Kabelcurl med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'flat-bench-cable-flys.png' WHERE name = 'Kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'cable-crossover.png' WHERE name = 'Kabelkorsning' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-cable-rows.png' WHERE name = 'Kabelrodd sittande' AND category = 'strength';
UPDATE exercises SET image_path = 'barbell-squat.png' WHERE name = 'Knäböj' AND category = 'strength';
UPDATE exercises SET image_path = 'concentration-curls-with-dumbbell.png' WHERE name = 'Koncentrationscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'underhand-pull-downs.png' WHERE name = 'Latsdrag framifrån' AND category = 'strength';
UPDATE exercises SET image_path = 'straight-arm-push-down.png' WHERE name = 'Latsdrag med raka armar' AND category = 'strength';
UPDATE exercises SET image_path = 'v-bar-pull-down.png' WHERE name = 'Latsdrag smalt grepp' AND category = 'strength';
UPDATE exercises SET image_path = 'incline-bench-press.png' WHERE name = 'Lutande bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'incline-dumbbell-press.png' WHERE name = 'Lutande hantelpress' AND category = 'strength';
UPDATE exercises SET image_path = 'incline-cable-flys.png' WHERE name = 'Lutande kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'barbell-dead-lifts.png' WHERE name = 'Marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-military-press.png' WHERE name = 'Militärpress' AND category = 'strength';
UPDATE exercises SET image_path = 'lying-rear-lateral-raise.png' WHERE name = 'Omvänd flyes' AND category = 'strength';
UPDATE exercises SET image_path = 'single-leg-squat-with-barbell.png' WHERE name = 'Pistol squat' AND category = 'strength';
UPDATE exercises SET image_path = 'preacher-curl-with-barbell.png' WHERE name = 'Preacher curl' AND category = 'strength';
UPDATE exercises SET image_path = 'pull-ups.png' WHERE name = 'Pull-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'push-ups.png' WHERE name = 'Push-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'reverse-grips-bent-over-barbell-rows.png' WHERE name = 'Rodd med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'romanian-dead-lift.png' WHERE name = 'Rumänsk marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'shoulder-shrugs.png' WHERE name = 'Shrugs med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'barbell-shrugs.png' WHERE name = 'Shrugs med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'lateral-dumbbell-raises.png' WHERE name = 'Sidolyft' AND category = 'strength';
UPDATE exercises SET image_path = 'side-plank.png' WHERE name = 'Sidoplanka' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-leg-curl.png' WHERE name = 'Sittande bencurl' AND category = 'strength';
UPDATE exercises SET image_path = 'seated-calf-raise-using-machine.png' WHERE name = 'Sittande vadpress' AND category = 'strength';
UPDATE exercises SET image_path = 'lying-triceps-press-with-barbell.png' WHERE name = 'Skull crushers' AND category = 'strength';
UPDATE exercises SET image_path = 'close-grip-barbell-bench-press.png' WHERE name = 'Smalbänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'step-ups-with-barbell.png' WHERE name = 'Steg-ups' AND category = 'strength';
UPDATE exercises SET image_path = 't-bar-rows.png' WHERE name = 'T-bar rodd' AND category = 'strength';
UPDATE exercises SET image_path = 'triceps-kickback-with-dumbbell.png' WHERE name = 'Triceps kickback' AND category = 'strength';
UPDATE exercises SET image_path = 'lying-close-grip-triceps-press-to-chin-with-barbell.png' WHERE name = 'Tricepspress smal' AND category = 'strength';
UPDATE exercises SET image_path = 'triceps-pushdown-with-cable.png' WHERE name = 'Tricepsstötning kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'triceps-pushdown-with-rope-and-cable.png' WHERE name = 'Tricepsstötning med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'upright-barbell-rows.png' WHERE name = 'Upright row' AND category = 'strength';
UPDATE exercises SET image_path = 'dumbbell-lunges.png' WHERE name = 'Utfall' AND category = 'strength';
UPDATE exercises SET image_path = 'standing-calf-raises-using-machine.png' WHERE name = 'Vadpress stående' AND category = 'strength';
