-- Utrustning backfylls för ursprungsbiblioteket (kolumnen kom med egna
-- övningar, originalen fick aldrig värden) så utrustningsfiltret träffar
-- hela biblioteket. Värdena kommer från ExerciseDB-mappningen. Idempotent.

UPDATE exercises SET equipment = 'other' WHERE name = 'Ab wheel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Arnold press' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Axellyft med kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Bakre deltalyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Bakre deltalyft i kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Bencurl liggande' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Benextension' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Benlyft liggande' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Benpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Bicepscurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Box squat' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Bulgariska utfall' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Bänkpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Chin-ups' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Crunches' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Decline bänkpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Dips' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Dragon flag' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Enarms hantelrodd' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Enarms kabelcurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Enarms kabelrodd' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Face pulls' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Farmers walk' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Flyes med hantlar' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Frivändning' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Front squat' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Frontlyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Frontlyft i kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Genomdrag med kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Glute kickback i kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Goblet squat' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Good mornings' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Hack squat' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Hammercurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Handledscurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Hantelpress axlar' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Hantelpress liggande' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Hip thrust' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Hyperextensions' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Hängande benlyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Höftabduktion i kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelbiceps' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelcrunch' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelcurl med rep' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelflyes' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelkorsning' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelpullover' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelrodd sittande' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabeltriceps över huvud' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Kabelvridning' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'kettlebell' WHERE name = 'Kettlebell swing' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Knäböj' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Koncentrationscurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Latsdrag bakåt' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Latsdrag framifrån' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Latsdrag med raka armar' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Latsdrag smalt grepp' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Lutande bänkpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Lutande hantelpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Lutande kabelflyes' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Marklyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Militärpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Mountain climbers' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Nordic curl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Omvänd flyes' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'band' WHERE name = 'Pallof press' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Pec deck' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'kettlebell' WHERE name = 'Pistol squat' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'other' WHERE name = 'Plankan' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Preacher curl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Pull-ups' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Push press' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Push-ups' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Rack pull' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Rodd med skivstång' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Rumänsk marklyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Russian twist' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Shrugs med hantlar' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Shrugs med skivstång' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Sidolyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Sidoplanka' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'Sittande bencurl' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Sittande vadpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'none' WHERE name = 'Situps' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Skull crushers' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Smalbänkpress' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Steg-ups' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Stående kabelrodd' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Sumo marklyft' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'machine' WHERE name = 'T-bar rodd' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Thrusters' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Triceps kickback' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Tricepspress smal' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Tricepsstötning kabel' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'cable' WHERE name = 'Tricepsstötning med rep' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Upright row' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'dumbbell' WHERE name = 'Utfall' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Vadpress stående' AND user_id IS NULL AND equipment IS NULL;
UPDATE exercises SET equipment = 'barbell' WHERE name = 'Landmine press' AND user_id IS NULL AND equipment IS NULL;
