-- Licensierade ExerciseDB-GIF:ar (köpt self-hosted-paket) ersätter
-- illustrationerna där de matchar. Endast delmängden appen använder
-- laddas upp, per EULA §9. Idempotent.

UPDATE exercises SET image_path = 'ab-wheel.gif' WHERE name = 'Ab wheel' AND category = 'strength';
UPDATE exercises SET image_path = 'arnold-press.gif' WHERE name = 'Arnold press' AND category = 'strength';
UPDATE exercises SET image_path = 'axellyft-med-kabel.gif' WHERE name = 'Axellyft med kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'bakre-deltalyft.gif' WHERE name = 'Bakre deltalyft' AND category = 'strength';
UPDATE exercises SET image_path = 'bakre-deltalyft-i-kabel.gif' WHERE name = 'Bakre deltalyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'bencurl-liggande.gif' WHERE name = 'Bencurl liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'benextension.gif' WHERE name = 'Benextension' AND category = 'strength';
UPDATE exercises SET image_path = 'benlyft-liggande.gif' WHERE name = 'Benlyft liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'benpress.gif' WHERE name = 'Benpress' AND category = 'strength';
UPDATE exercises SET image_path = 'bicepscurl.gif' WHERE name = 'Bicepscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'box-squat.gif' WHERE name = 'Box squat' AND category = 'strength';
UPDATE exercises SET image_path = 'bulgariska-utfall.gif' WHERE name = 'Bulgariska utfall' AND category = 'strength';
UPDATE exercises SET image_path = 'bankpress.gif' WHERE name = 'Bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'chin-ups.gif' WHERE name = 'Chin-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'crunches.gif' WHERE name = 'Crunches' AND category = 'strength';
UPDATE exercises SET image_path = 'decline-bankpress.gif' WHERE name = 'Decline bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'dips.gif' WHERE name = 'Dips' AND category = 'strength';
UPDATE exercises SET image_path = 'dragon-flag.gif' WHERE name = 'Dragon flag' AND category = 'strength';
UPDATE exercises SET image_path = 'enarms-hantelrodd.gif' WHERE name = 'Enarms hantelrodd' AND category = 'strength';
UPDATE exercises SET image_path = 'enarms-kabelcurl.gif' WHERE name = 'Enarms kabelcurl' AND category = 'strength';
UPDATE exercises SET image_path = 'enarms-kabelrodd.gif' WHERE name = 'Enarms kabelrodd' AND category = 'strength';
UPDATE exercises SET image_path = 'face-pulls.gif' WHERE name = 'Face pulls' AND category = 'strength';
UPDATE exercises SET image_path = 'farmers-walk.gif' WHERE name = 'Farmers walk' AND category = 'strength';
UPDATE exercises SET image_path = 'flyes-med-hantlar.gif' WHERE name = 'Flyes med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'frivandning.gif' WHERE name = 'Frivändning' AND category = 'strength';
UPDATE exercises SET image_path = 'front-squat.gif' WHERE name = 'Front squat' AND category = 'strength';
UPDATE exercises SET image_path = 'frontlyft.gif' WHERE name = 'Frontlyft' AND category = 'strength';
UPDATE exercises SET image_path = 'frontlyft-i-kabel.gif' WHERE name = 'Frontlyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'genomdrag-med-kabel.gif' WHERE name = 'Genomdrag med kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'glute-kickback-i-kabel.gif' WHERE name = 'Glute kickback i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'goblet-squat.gif' WHERE name = 'Goblet squat' AND category = 'strength';
UPDATE exercises SET image_path = 'good-mornings.gif' WHERE name = 'Good mornings' AND category = 'strength';
UPDATE exercises SET image_path = 'hack-squat.gif' WHERE name = 'Hack squat' AND category = 'strength';
UPDATE exercises SET image_path = 'hammercurl.gif' WHERE name = 'Hammercurl' AND category = 'strength';
UPDATE exercises SET image_path = 'handledscurl.gif' WHERE name = 'Handledscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'hantelpress-axlar.gif' WHERE name = 'Hantelpress axlar' AND category = 'strength';
UPDATE exercises SET image_path = 'hantelpress-liggande.gif' WHERE name = 'Hantelpress liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'hip-thrust.gif' WHERE name = 'Hip thrust' AND category = 'strength';
UPDATE exercises SET image_path = 'hyperextensions.gif' WHERE name = 'Hyperextensions' AND category = 'strength';
UPDATE exercises SET image_path = 'hangande-benlyft.gif' WHERE name = 'Hängande benlyft' AND category = 'strength';
UPDATE exercises SET image_path = 'hoftabduktion-i-kabel.gif' WHERE name = 'Höftabduktion i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelbiceps.gif' WHERE name = 'Kabelbiceps' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelcrunch.gif' WHERE name = 'Kabelcrunch' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelcurl-med-rep.gif' WHERE name = 'Kabelcurl med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelflyes.gif' WHERE name = 'Kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelkorsning.gif' WHERE name = 'Kabelkorsning' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelpress.gif' WHERE name = 'Kabelpress' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelpullover.gif' WHERE name = 'Kabelpullover' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelrodd-sittande.gif' WHERE name = 'Kabelrodd sittande' AND category = 'strength';
UPDATE exercises SET image_path = 'kabeltriceps-over-huvud.gif' WHERE name = 'Kabeltriceps över huvud' AND category = 'strength';
UPDATE exercises SET image_path = 'kabelvridning.gif' WHERE name = 'Kabelvridning' AND category = 'strength';
UPDATE exercises SET image_path = 'kettlebell-swing.gif' WHERE name = 'Kettlebell swing' AND category = 'strength';
UPDATE exercises SET image_path = 'knaboj.gif' WHERE name = 'Knäböj' AND category = 'strength';
UPDATE exercises SET image_path = 'koncentrationscurl.gif' WHERE name = 'Koncentrationscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'latsdrag-bakat.gif' WHERE name = 'Latsdrag bakåt' AND category = 'strength';
UPDATE exercises SET image_path = 'latsdrag-framifran.gif' WHERE name = 'Latsdrag framifrån' AND category = 'strength';
UPDATE exercises SET image_path = 'latsdrag-med-raka-armar.gif' WHERE name = 'Latsdrag med raka armar' AND category = 'strength';
UPDATE exercises SET image_path = 'latsdrag-smalt-grepp.gif' WHERE name = 'Latsdrag smalt grepp' AND category = 'strength';
UPDATE exercises SET image_path = 'lutande-bankpress.gif' WHERE name = 'Lutande bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'lutande-hantelpress.gif' WHERE name = 'Lutande hantelpress' AND category = 'strength';
UPDATE exercises SET image_path = 'lutande-kabelflyes.gif' WHERE name = 'Lutande kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'marklyft.gif' WHERE name = 'Marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'militarpress.gif' WHERE name = 'Militärpress' AND category = 'strength';
UPDATE exercises SET image_path = 'mountain-climbers.gif' WHERE name = 'Mountain climbers' AND category = 'strength';
UPDATE exercises SET image_path = 'nordic-curl.gif' WHERE name = 'Nordic curl' AND category = 'strength';
UPDATE exercises SET image_path = 'omvand-flyes.gif' WHERE name = 'Omvänd flyes' AND category = 'strength';
UPDATE exercises SET image_path = 'pallof-press.gif' WHERE name = 'Pallof press' AND category = 'strength';
UPDATE exercises SET image_path = 'pec-deck.gif' WHERE name = 'Pec deck' AND category = 'strength';
UPDATE exercises SET image_path = 'pistol-squat.gif' WHERE name = 'Pistol squat' AND category = 'strength';
UPDATE exercises SET image_path = 'plankan.gif' WHERE name = 'Plankan' AND category = 'strength';
UPDATE exercises SET image_path = 'preacher-curl.gif' WHERE name = 'Preacher curl' AND category = 'strength';
UPDATE exercises SET image_path = 'pull-ups.gif' WHERE name = 'Pull-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'push-press.gif' WHERE name = 'Push press' AND category = 'strength';
UPDATE exercises SET image_path = 'push-ups.gif' WHERE name = 'Push-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'rack-pull.gif' WHERE name = 'Rack pull' AND category = 'strength';
UPDATE exercises SET image_path = 'rodd-med-skivstang.gif' WHERE name = 'Rodd med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'rumansk-marklyft.gif' WHERE name = 'Rumänsk marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'russian-twist.gif' WHERE name = 'Russian twist' AND category = 'strength';
UPDATE exercises SET image_path = 'shrugs-med-hantlar.gif' WHERE name = 'Shrugs med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'shrugs-med-skivstang.gif' WHERE name = 'Shrugs med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'sidolyft.gif' WHERE name = 'Sidolyft' AND category = 'strength';
UPDATE exercises SET image_path = 'sidoplanka.gif' WHERE name = 'Sidoplanka' AND category = 'strength';
UPDATE exercises SET image_path = 'sittande-bencurl.gif' WHERE name = 'Sittande bencurl' AND category = 'strength';
UPDATE exercises SET image_path = 'sittande-vadpress.gif' WHERE name = 'Sittande vadpress' AND category = 'strength';
UPDATE exercises SET image_path = 'situps.gif' WHERE name = 'Situps' AND category = 'strength';
UPDATE exercises SET image_path = 'skull-crushers.gif' WHERE name = 'Skull crushers' AND category = 'strength';
UPDATE exercises SET image_path = 'smalbankpress.gif' WHERE name = 'Smalbänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'steg-ups.gif' WHERE name = 'Steg-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'staende-kabelrodd.gif' WHERE name = 'Stående kabelrodd' AND category = 'strength';
UPDATE exercises SET image_path = 'sumo-marklyft.gif' WHERE name = 'Sumo marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 't-bar-rodd.gif' WHERE name = 'T-bar rodd' AND category = 'strength';
UPDATE exercises SET image_path = 'thrusters.gif' WHERE name = 'Thrusters' AND category = 'strength';
UPDATE exercises SET image_path = 'triceps-kickback.gif' WHERE name = 'Triceps kickback' AND category = 'strength';
UPDATE exercises SET image_path = 'tricepspress-smal.gif' WHERE name = 'Tricepspress smal' AND category = 'strength';
UPDATE exercises SET image_path = 'tricepsstotning-kabel.gif' WHERE name = 'Tricepsstötning kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'tricepsstotning-med-rep.gif' WHERE name = 'Tricepsstötning med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'upright-row.gif' WHERE name = 'Upright row' AND category = 'strength';
UPDATE exercises SET image_path = 'utfall.gif' WHERE name = 'Utfall' AND category = 'strength';
UPDATE exercises SET image_path = 'vadpress-staende.gif' WHERE name = 'Vadpress stående' AND category = 'strength';
