-- Övningsbilder från free-exercise-db (public domain, Unlicense).
-- Bilderna ligger i den publika bucketen exercise-images, appen bygger
-- URL:en från image_path. Idempotent.

INSERT INTO storage.buckets (id, name, public)
VALUES ('exercise-images', 'exercise-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

ALTER TABLE exercises ADD COLUMN IF NOT EXISTS image_path text;

UPDATE exercises SET image_path = 'Ab_Roller.jpg' WHERE name = 'Ab wheel' AND category = 'strength';
UPDATE exercises SET image_path = 'Arnold_Dumbbell_Press.jpg' WHERE name = 'Arnold press' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Seated_Lateral_Raise.jpg' WHERE name = 'Axellyft med kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_Bent-Over_Rear_Delt_Raise.jpg' WHERE name = 'Bakre deltalyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Rear_Delt_Fly.jpg' WHERE name = 'Bakre deltalyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Lying_Leg_Curls.jpg' WHERE name = 'Bencurl liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'Leg_Extensions.jpg' WHERE name = 'Benextension' AND category = 'strength';
UPDATE exercises SET image_path = 'Flat_Bench_Lying_Leg_Raise.jpg' WHERE name = 'Benlyft liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'Leg_Press.jpg' WHERE name = 'Benpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Curl.jpg' WHERE name = 'Bicepscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Box_Squat.jpg' WHERE name = 'Box squat' AND category = 'strength';
UPDATE exercises SET image_path = 'Split_Squats.jpg' WHERE name = 'Bulgariska utfall' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Bench_Press_-_Medium_Grip.jpg' WHERE name = 'Bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Chin-Up.jpg' WHERE name = 'Chin-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'Crunches.jpg' WHERE name = 'Crunches' AND category = 'strength';
UPDATE exercises SET image_path = 'Decline_Barbell_Bench_Press.jpg' WHERE name = 'Decline bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Parallel_Bar_Dip.jpg' WHERE name = 'Dips' AND category = 'strength';
UPDATE exercises SET image_path = 'One-Arm_Dumbbell_Row.jpg' WHERE name = 'Enarms hantelrodd' AND category = 'strength';
UPDATE exercises SET image_path = 'Standing_One-Arm_Cable_Curl.jpg' WHERE name = 'Enarms kabelcurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_One-arm_Cable_Pulley_Rows.jpg' WHERE name = 'Enarms kabelrodd' AND category = 'strength';
UPDATE exercises SET image_path = 'Face_Pull.jpg' WHERE name = 'Face pulls' AND category = 'strength';
UPDATE exercises SET image_path = 'Farmers_Walk.jpg' WHERE name = 'Farmers walk' AND category = 'strength';
UPDATE exercises SET image_path = 'Dumbbell_Flyes.jpg' WHERE name = 'Flyes med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'Power_Clean.jpg' WHERE name = 'Frivändning' AND category = 'strength';
UPDATE exercises SET image_path = 'Front_Barbell_Squat.jpg' WHERE name = 'Front squat' AND category = 'strength';
UPDATE exercises SET image_path = 'Front_Dumbbell_Raise.jpg' WHERE name = 'Frontlyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Front_Cable_Raise.jpg' WHERE name = 'Frontlyft i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Pull_Through.jpg' WHERE name = 'Genomdrag med kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'One-Legged_Cable_Kickback.jpg' WHERE name = 'Glute kickback i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Goblet_Squat.jpg' WHERE name = 'Goblet squat' AND category = 'strength';
UPDATE exercises SET image_path = 'Good_Morning.jpg' WHERE name = 'Good mornings' AND category = 'strength';
UPDATE exercises SET image_path = 'Hack_Squat.jpg' WHERE name = 'Hack squat' AND category = 'strength';
UPDATE exercises SET image_path = 'Hammer_Curls.jpg' WHERE name = 'Hammercurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_Palm-Up_Barbell_Wrist_Curl.jpg' WHERE name = 'Handledscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Dumbbell_Shoulder_Press.jpg' WHERE name = 'Hantelpress axlar' AND category = 'strength';
UPDATE exercises SET image_path = 'Dumbbell_Bench_Press.jpg' WHERE name = 'Hantelpress liggande' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Hip_Thrust.jpg' WHERE name = 'Hip thrust' AND category = 'strength';
UPDATE exercises SET image_path = 'Hyperextensions_Back_Extensions.jpg' WHERE name = 'Hyperextensions' AND category = 'strength';
UPDATE exercises SET image_path = 'Hanging_Leg_Raise.jpg' WHERE name = 'Hängande benlyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Thigh_Abductor.jpg' WHERE name = 'Höftabduktion i kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Standing_Biceps_Cable_Curl.jpg' WHERE name = 'Kabelbiceps' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Crunch.jpg' WHERE name = 'Kabelcrunch' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Hammer_Curls_-_Rope_Attachment.jpg' WHERE name = 'Kabelcurl med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'Flat_Bench_Cable_Flyes.jpg' WHERE name = 'Kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Crossover.jpg' WHERE name = 'Kabelkorsning' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Chest_Press.jpg' WHERE name = 'Kabelpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Straight-Arm_Dumbbell_Pullover.jpg' WHERE name = 'Kabelpullover' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_Cable_Rows.jpg' WHERE name = 'Kabelrodd sittande' AND category = 'strength';
UPDATE exercises SET image_path = 'Cable_Rope_Overhead_Triceps_Extension.jpg' WHERE name = 'Kabeltriceps över huvud' AND category = 'strength';
UPDATE exercises SET image_path = 'Standing_Cable_Wood_Chop.jpg' WHERE name = 'Kabelvridning' AND category = 'strength';
UPDATE exercises SET image_path = 'One-Arm_Kettlebell_Swings.jpg' WHERE name = 'Kettlebell swing' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Squat.jpg' WHERE name = 'Knäböj' AND category = 'strength';
UPDATE exercises SET image_path = 'Concentration_Curls.jpg' WHERE name = 'Koncentrationscurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Landmine_Linear_Jammer.jpg' WHERE name = 'Landmine press' AND category = 'strength';
UPDATE exercises SET image_path = 'Wide-Grip_Pulldown_Behind_The_Neck.jpg' WHERE name = 'Latsdrag bakåt' AND category = 'strength';
UPDATE exercises SET image_path = 'Wide-Grip_Lat_Pulldown.jpg' WHERE name = 'Latsdrag framifrån' AND category = 'strength';
UPDATE exercises SET image_path = 'Straight-Arm_Pulldown.jpg' WHERE name = 'Latsdrag med raka armar' AND category = 'strength';
UPDATE exercises SET image_path = 'Close-Grip_Front_Lat_Pulldown.jpg' WHERE name = 'Latsdrag smalt grepp' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Incline_Bench_Press_-_Medium_Grip.jpg' WHERE name = 'Lutande bänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Incline_Dumbbell_Press.jpg' WHERE name = 'Lutande hantelpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Incline_Cable_Flye.jpg' WHERE name = 'Lutande kabelflyes' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Deadlift.jpg' WHERE name = 'Marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Standing_Military_Press.jpg' WHERE name = 'Militärpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Mountain_Climbers.jpg' WHERE name = 'Mountain climbers' AND category = 'strength';
UPDATE exercises SET image_path = 'Natural_Glute_Ham_Raise.jpg' WHERE name = 'Nordic curl' AND category = 'strength';
UPDATE exercises SET image_path = 'Reverse_Flyes.jpg' WHERE name = 'Omvänd flyes' AND category = 'strength';
UPDATE exercises SET image_path = 'Pallof_Press.jpg' WHERE name = 'Pallof press' AND category = 'strength';
UPDATE exercises SET image_path = 'Butterfly.jpg' WHERE name = 'Pec deck' AND category = 'strength';
UPDATE exercises SET image_path = 'Kettlebell_Pistol_Squat.jpg' WHERE name = 'Pistol squat' AND category = 'strength';
UPDATE exercises SET image_path = 'Plank.jpg' WHERE name = 'Plankan' AND category = 'strength';
UPDATE exercises SET image_path = 'Preacher_Curl.jpg' WHERE name = 'Preacher curl' AND category = 'strength';
UPDATE exercises SET image_path = 'Pullups.jpg' WHERE name = 'Pull-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'Push_Press.jpg' WHERE name = 'Push press' AND category = 'strength';
UPDATE exercises SET image_path = 'Pushups.jpg' WHERE name = 'Push-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'Rack_Pulls.jpg' WHERE name = 'Rack pull' AND category = 'strength';
UPDATE exercises SET image_path = 'Bent_Over_Barbell_Row.jpg' WHERE name = 'Rodd med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'Romanian_Deadlift.jpg' WHERE name = 'Rumänsk marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Russian_Twist.jpg' WHERE name = 'Russian twist' AND category = 'strength';
UPDATE exercises SET image_path = 'Dumbbell_Shrug.jpg' WHERE name = 'Shrugs med hantlar' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Shrug.jpg' WHERE name = 'Shrugs med skivstång' AND category = 'strength';
UPDATE exercises SET image_path = 'Side_Lateral_Raise.jpg' WHERE name = 'Sidolyft' AND category = 'strength';
UPDATE exercises SET image_path = 'Side_Bridge.jpg' WHERE name = 'Sidoplanka' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_Leg_Curl.jpg' WHERE name = 'Sittande bencurl' AND category = 'strength';
UPDATE exercises SET image_path = 'Seated_Calf_Raise.jpg' WHERE name = 'Sittande vadpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Sit-Up.jpg' WHERE name = 'Situps' AND category = 'strength';
UPDATE exercises SET image_path = 'EZ-Bar_Skullcrusher.jpg' WHERE name = 'Skull crushers' AND category = 'strength';
UPDATE exercises SET image_path = 'Close-Grip_Barbell_Bench_Press.jpg' WHERE name = 'Smalbänkpress' AND category = 'strength';
UPDATE exercises SET image_path = 'Barbell_Step_Ups.jpg' WHERE name = 'Steg-ups' AND category = 'strength';
UPDATE exercises SET image_path = 'Sumo_Deadlift.jpg' WHERE name = 'Sumo marklyft' AND category = 'strength';
UPDATE exercises SET image_path = 'T-Bar_Row_with_Handle.jpg' WHERE name = 'T-bar rodd' AND category = 'strength';
UPDATE exercises SET image_path = 'Kettlebell_Thruster.jpg' WHERE name = 'Thrusters' AND category = 'strength';
UPDATE exercises SET image_path = 'Tricep_Dumbbell_Kickback.jpg' WHERE name = 'Triceps kickback' AND category = 'strength';
UPDATE exercises SET image_path = 'Close-Grip_Barbell_Bench_Press.jpg' WHERE name = 'Tricepspress smal' AND category = 'strength';
UPDATE exercises SET image_path = 'Triceps_Pushdown.jpg' WHERE name = 'Tricepsstötning kabel' AND category = 'strength';
UPDATE exercises SET image_path = 'Triceps_Pushdown_-_Rope_Attachment.jpg' WHERE name = 'Tricepsstötning med rep' AND category = 'strength';
UPDATE exercises SET image_path = 'Upright_Barbell_Row.jpg' WHERE name = 'Upright row' AND category = 'strength';
UPDATE exercises SET image_path = 'Dumbbell_Lunges.jpg' WHERE name = 'Utfall' AND category = 'strength';
UPDATE exercises SET image_path = 'Standing_Calf_Raises.jpg' WHERE name = 'Vadpress stående' AND category = 'strength';
